### ISSUE TITLE
Recurse on multiple keys

### ISSUE THREAD

**Issue by baskerville** [stedolan/jq#1029]
If the children of a binary tree aren't contained inside an array but are specified as keys, is there a way to recurse on both keys?

**Comment by nicowilliams** [comment]
The recursive traversal operators in jq work on arrays and objects.  See `..` for example.

**Comment by baskerville** [comment]
Thanks, `..` is great, I reached my goal with: `..|objects|select(.foo!=null)|.foo`.

**Comment by baskerville** [comment]
It seems I can make it shorter: `..|.foo?|values`.

**Comment by nicowilliams** [comment]
Glad that helped!

(This is kinda similar to XPath, where one would use `//foo` where in jq one would use `..|.foo?`.  The price XPath pays for using `/` as a path component separator is that it needs a `div` operator, but paths are a very common thing when dealing with hierarchical data; OTOH, `.` works well too because that's what one would use in many programming languages.)
