### ISSUE TITLE
Feature request: a '//' that also applies to empty strings

### ISSUE THREAD

**Issue by fj** [stedolan/jq#1275]
One sometimes wants a missing value to be present in some form in the output, regardless of whether:

* the key is missing entirely or
* the key is present, but the corresponding value is the empty string ("")

To that end, I would like to propose a new operator. For purposes of this issue, we'll call it `///`, by analogy with the existing alternative operator `//`. This operator would have the same functionality as `//`, but would also return its right-hand side when the left-hand side is an empty string.

Currently, for `a // b`:

| condition | result |
| - | - |
| when `a` is neither empty nor null | `a` |
| when `a` is empty, but not null | `a` |
| when `a` is null | `b` |

With the proposed operator `a /// b`, the second row of this table changes. That is, for `a /// b`:

| condition | result |
| - | - |
| when `a` is neither empty nor null | `a` |
| when `a` is empty, but not null | `b` |
| when `a` is null | `b` |

Does this make sense? Is there value to others in this use case?

**Comment by pkoppstein** [comment]
@fj - Please note that in jq, `a // b` is defined when a and b are (possibly empty) streams of JSON entities. For example, `empty // false` yields `false`, `false // empty` yields the empty stream, and `false // (3,4)` yields the stream 3, 4.

It would therefore be helpful if you could update your proposal accordingly.  It would probably also be helpful if you distinguished between jq's `empty` (a stream of length 0), `[]` (the empty array), and `{}` (the empty object).

Because both `a or b` and `a // b` emit b if a is null or false, the difficulty before jq 1.5 was to test  whether a stream, s, is empty without iterating through the entire stream.

Fortunately, with the introduction of `any/2`, one can now simply write `any(s; true)`



    def isempty(s); foreach s as $x (false; 

       

We could define isempty/1 as: def isempty(s): lto write if length(s) == 0 then false tween a stream of length 0 and a stream of length 1 without counting.

**Comment by fj** [comment]
@pkoppstein To be sure I understand you, are you asking for me to describe the expected results for the proposed operator when considering the three cases you raised (stream of length zero, the empty array, and the empty object), and therefore expand the two tables accordingly?

**Comment by pkoppstein** [comment]
@fj - It would probably be sufficient to cover these four cases: empty, false, null, and any other JSON value.

**Comment by fj** [comment]
@pkoppstein Wouldn't we need to consider the empty string `""`, as well? Without that I'm not sure how to capture the essence of the proposal.

**Comment by pkoppstein** [comment]
@fj - As I indicated, I was not sure what you meant by "empty".  I was essentially just asking that (a) you characterize `//` correctly for the four cases I mentioned, and (b) you be careful when making the distinctions that are relevant for your proposal.

Now that you have explained your proposal, though, I don't see the point, as the empty string is not a very special "special case", and distinguished values can easily be handled, by writing: `if a == VALUE then b else a//b end`, where VALUE is the distinguished value.

**Comment by fj** [comment]
@pkoppstein I agree with your assessment, this isn't necessary and it's just a special case of what you indicated. Will close this. Thanks!
