### ISSUE TITLE
Reading field into variables...

### ISSUE THREAD

**Issue by Zibri** [stedolan/jq#1299]
I now I can do:
$(wget url| jq .[0].data1)

but is there a way to get more than one in one shot and put into two different variables?

$(wget url| jq ".[0].data1, .[0].data2")   works...but...

...nevermind.. I solved it like this..

(wget -q "URL" -O -| jq ".[0].data1, .[0].data2") | (read a;read b;echo DATA1: $a DATA2: $b)

but tell me if there is an easier way.

**Comment by danilobellini** [comment]
Assuming that:

- The key names are valid shell variable names
- You want the variable names in uppercase

```shell
eval $(wget url
      | jq -r '.[0] | to_entries[]
                    | "\(.key | ascii_upcase)=\(.value | @sh)"
                    | @sh'
)
```

**Comment by pkoppstein** [comment]
Please see the [jq FAQ](https://github.com/stedolan/jq/wiki/FAQ), and in particular the questions:

> Q: How to extract parts of JSON into shell variables?

> Q: How can a stream of JSON texts produced by jq be converted into a bash array of corresponding values?

In short, use `jq` with the -e option, and if you do use`read`, use `read -r`.

**Comment by danilobellini** [comment]
The most important part for me is the `-r` option (the `jq` one, not the `read` one), which seems underdocumented. "*Unquote/print each result instead of its JSON representation when it's a string*" would be more clear as a help description.

Removing the outer quotes isn't easy without that option, it would require prepending `eval echo` with either awk/sed/printf to run it with `xargs -d'\n' -n1 sh -c` afterwards, and wouldn't work if there's any line feed in the contents. I almost answered here with that double eval+echo+xargs solution, because I found it before knowing about `-r`, though I had seen the FAQ way before that, and I was already looking for "unquote" and stuff alike when I did so. Actually, the FAQ says that "*jq has a way to format text in a shell-safe way*" but doesn't emphasize that both `@sh` and `-r` are required (at first, I missed the `-r`).

As `xargs` breaks on the escaped quote inside strings (calling `jq` without the `-r` option), it's hard to tell how essential is that option to use the `jq` result for further processing on strings. As an example based on a FAQ example:

```shell
$ jq -n '"a\t with \"b\" quoted","c"| @sh' | xargs
xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option
'a\t with \b"
```

And the `"c"` vanished away because of that error. As it seems, `xargs` reads the backslash as a common character, not as a escaping symbol.

```shell
$ jq -rn '"a\t with \"b\" quoted","c"| @sh' | xargs -d'\n'
'a	 with "b" quoted' 'c'
```

And when one is storing the result as an array...

```shell
$ data=( $(jq -n '"a\t with \"b\" quoted","c"| @sh' )  )
$ echo ${data[0]}
"'a\t
```

I strongly believe a user would probably want a `a	 with "b" quoted` result, not that `"'a\t`.

So I'd say one should [almost] always use the `-r` option when the result is a string.

> Q: How can a stream of JSON texts produced by jq be converted into a bash array of corresponding values?

About that FAQ entry, if one is already using bash, wouldn't mapfile/readarray be easier?

```shell
mapfile -t array <<< $(jq -c '.[]' input.json)
```
