### ISSUE TITLE
Can't sub dot

### ISSUE THREAD

**Issue by dolvany** [stedolan/jq#1307]
dolvany:~ dolvany$ jq -n '"vip_doijwe.com_443"|sub("_";"";"g")'
"vipdoijwe.com443"
dolvany:~ dolvany$ jq -n '"vip_doijwe.com_443"|sub(".";"";"g")'
""
dolvany:~ dolvany$

**Comment by slapresta** [comment]
`sub` takes a regular expression as an argument; on regular expressions, `.` represents any character. Therefore, `sub` is doing exactly what it's supposed to; it's replacing all characters with the empty string.

You could escape the dot on the jq program; since the dot is inside a string in a jq program, which is itself a string in a shell application, you will need four backslashes to escape it:

`jq -n '"vip_doijwe.com_443"|sub("\\\\.";"";"g")'`

**Comment by dolvany** [comment]
Based on your advice, I was able to get it working with a double-backslash. The quadruple backslash did not seem to work. May be a good one to add to the man page. Thanks for the assist!

dolvany:~ dolvany$ jq -n '"vip_doijwe.com_443"|sub("\\.";"";"g")'
"vip_doijwecom_443"
dolvany:~ dolvany$ jq -n '"vip_doijwe.com_443"|sub("\\\\.";"";"g")'
"vip_doijwe.com_443"
dolvany:~ dolvany$
