### ISSUE TITLE
Add builtin that outputs list of builtins

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#1318]
```
jq -n builtins
```
should list all public builtins.

**Comment by wtlangford** [comment]
Unfortunately, I don't think jq has the meta programming power to do this automatically. Although, I think it could possibly be done in c land, if we're clever. Alternatively, we could manually manage a list?

**Comment by nicowilliams** [comment]
Yeah, this has to be coded in C.

**Comment by wtlangford** [comment]
@nicowilliams I'm working on this and I've noticed that we actually have two copies of each libm.h function: `name` and `_name`.
The `name` variants are defined as such:
```
#define LIBM_DD(name) "def " #name ": _" #name ";"
#define LIBM_DDD(name) "def " #name "(a;b): _" #name "(a;b);"
#define LIBM_DDDD(name) "def " #name "(a;b;c): _" #name "(a;b;c);"
```
and the `_name` variants are `cfunction`s.
Since the `name` versions are just passthrough shims in over the `cfunction`s, I'm going to make the `name` versions the `cfunction`s, and skip the extra call frame.  I'll leave the `LIBM_DD*_NO` macros (they emit stubs for missing libm functions at this phase) as is.

That is, unless there's a good reason they're built this way?

Also- how are we defining "public" builtins for this? Is that just "builtins that are listed in the documentation" or "anything without a leading _" or "any function you can call from a main program that doesn't contain any defs or imports"?

**Comment by nicowilliams** [comment]
Hmm, no, actually, I can't think of a good reason it's this way.  I must have screwed that up.

**Comment by nicowilliams** [comment]
I guess public should mean "documented", but that's tricky, so, "without leading _" will have to be the rule.

**Comment by wtlangford** [comment]
Alright, I'll exclude things that start with `_` from the list, remove those `_name` math functions, and clean up a memory leak I noticed in the error cases for those functions while I'm there.

**Comment by wtlangford** [comment]
Do we want this list to be sorted?

**Comment by pkoppstein** [comment]
@wtlangford - The very last entry in the array produced by `builtins` is "builtins"; for consistency, it should be "builtins/0", no?

    $ jq -n 'builtins[-1]'
    "builtins"

**Comment by wtlangford** [comment]
Haha, yes it should. The secret is that I manually add `builtins` to the
list, and forgot the format when I did it.
