### ISSUE TITLE
`autoreconf -i` fails on a Mac

### ISSUE THREAD

**Issue by pkoppstein** [stedolan/jq#1324]
Recently, de novo installation fails on a Mac due to a dependence on /usr/local/Library/ENV/4.3/sed

Apparently this is Travis-related.

In any case, creating a symbolic link to sed resolved the issue.

**Comment by wtlangford** [comment]
The brew version works, but required a reinstall post some upgrade (OS or
brew, I'm not sure)

**Comment by pkoppstein** [comment]
I should have clarified that the failures I have experienced have nothing to do with homebrew. They arise after using `git clone`.

**Comment by wtlangford** [comment]
My bad, my message was very misleading.  I was referring to the brew
version of libtool, which installs tools called `glibtool` and
`glibtoolize`, which autoreconf will use.  The problem here lies with
libtool.  My version of glibtoolize was broken and a `brew reinstall
libtool` fixed it.  I'm not sure it's necessarily a bug, though.

What do you mean by Travis-related?

**Comment by pkoppstein** [comment]
@wtlangford - Thanks. `brew upgrade libtool` fixed the problem, which I still find odd, largely because I'd been using the brew-installed libtool (v. 2.4.2) since 2013-02-25.

(My speculation about the problem possibly being Travis-related was mainly the result of some googling.)

**Comment by wtlangford** [comment]
Yeah, if you've upgraded brew or your OS recently, that might be related. I
know I had some issues post a brew upgrade but I don't remember why

On Fri, Jan 27, 2017, 00:37 pkoppstein <notifications@github.com> wrote:

@wtlangford <https://github.com/wtlangford> - Thanks. brew upgrade libtool
fixed the problem, which I still find odd, largely because I'd been using
the brew-installed libtool (v. 2.4.2) since 2013-02-25.

(My speculation about the problem possibly being Travis-related was mainly
the result of some googling.)

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/stedolan/jq/issues/1324#issuecomment-275592949>, or mute
the thread

**Comment by nicowilliams** [comment]
What should we do about this?  Update the README?

**Comment by pkoppstein** [comment]
I added some details at https://github.com/stedolan/jq/wiki/Installation

**Comment by nicowilliams** [comment]
Thanks @pkoppstein!
