### ISSUE TITLE
[BUG] Weird If conditional behaviour

### ISSUE THREAD

**Issue by jeanpralo** [stedolan/jq#1332]
Hi there,

I am a bit confused about the way the if condition is working.

Here is what I tested:

```
# echo '[{"host": "ch-toto"}, {"host": "toto"}]' | jq  'if .[].host | startswith("ch-") then "yes" else "no" end'
"yes"
"no"

# echo '[{"host": "ch-toto"}, {"host": "toto"}]' | jq  'if .[].host | startswith("ch-") then "YES - " + .[].host else "no" end'
"YES - ch-toto"
"YES - toto"
"no"

# echo '[{"host": "ch-toto"}, {"host": "toto"}]' | jq  'if .[].host | startswith("ch-") then "YES - .[].host" else "no" end'
"YES - .[].host"
"no"



# echo '[{"host": "ch-toto"}, {"host": "toto"}]' | jq  'if .[].host | startswith("ch-") then "YES - " + .[].host else "no - " + .[].host end'
"YES - ch-toto"
"YES - toto"
"no - ch-toto"
"no - toto"
```

It seems that every time we try to contextualize the variable we iterate every entries inside each condition.

Am not using the if statement properly ?

# jq  --version
jq-1.5-1-a5b5cbe

**Comment by wtlangford** [comment]
You're on the right track with it, though this isn't actually a bug.
What's happening here is that the input (`.`) to the `if` expression is your list (`[{"host": "ch-toto"}, {"host": "toto"}]`).
The if expression then attempts to evaluate its conditional expression, which receives the same input (the list).
The `.[]` in the conditional expression creates a sequence of outputs, so we make a forking point here and continue the program with each successive output.
For the first output, we pass `"ch-toto"` to `startswith/1`, which outputs `true`.  Since the conditional evaluated to true, we now run the true-branch of the if expression, `"YES - " + .[].host`.  The input to this expression is still the list from before, so this outputs the sequence (because of the forking from `.[]`): `"YES - ch-toto", "YES - toto"`.  Since there's nothing else to do now, the stack unwinds back to the previous fork point in the conditional expression and continues from there, this time going down the false-branch.

This forking behavior is a bit complicated to reason about at first (and forking probably isn't the best word, but it's the word we use in the code).

At any rate, an expression like this would solve your problem: 
```# echo '[{"host": "ch-toto"}, {"host": "toto"}]' | jq '.[] | if .host | startswith("ch-") then "YES - " + .host else "no - " + .host end'
"YES - ch-toto"
"no - toto"
```

Let me know if this is still confusing!

**Comment by jeanpralo** [comment]
Hey thanks for the explanation :)

What is the expression because I can only see the output results.

**Comment by wtlangford** [comment]
Ah! A bad copy paste!

```# echo '[{"host": "ch-toto"}, {"host": "toto"}]' | jq  '.[] | if .host | startswith("ch-") then "YES - " + .host else "no - " + .host end'
```

**Comment by jeanpralo** [comment]
Oh right got it :)

Thanks.
