### ISSUE TITLE
Add to FAQ :  What happens to data being pasted into jqplay ?

### ISSUE THREAD

**Issue by Phoenixxl** [stedolan/jq#1338]
It would be nice to have put in the FAQ a clear easy to find answer as to what happens to testdata pasted into the jqplay.org site.

Should one refrain from pasting in sensitive information ? 
( as a rule of thumb one should probably always avoid this ) 

Is it being sent to a server that parses it?
If it is, is it being kept there for a certain amount of time or until a certain amount of storage gets filled?
Is it being parsed by one's own browser using a java(or similar) jq applet running locally ?

I understand this info can be found by having a detailed look at the source but not every jq user is a programmer.

Thank you in advance for taking this update to the jq faq into consideration.
Friendly regards.

**Comment by Phoenixxl** [comment]
Closing. Posting in jqplay github page.

**Comment by nicowilliams** [comment]
Mind you, I would never paste proprietary information into anything like a pastebin, or jqplay, etcetera, not without first a) getting permission from an appropriate group, b) obfuscating the content as needed.

There's no need to ask what a pastebin or the like does with what you give them, and I would absolutely assume that they will log it (even if they say otherwise), not because I expect the worst from them, but because assuming the worst is good security practice that leads to the above advice.

IMO!
