### ISSUE TITLE
reduce example (array filtering) does not work as documented

### ISSUE THREAD

**Issue by frederik-elwert** [stedolan/jq#1446]
The second example from the documentation for `reduce` does not produce the result given in the documentation:

    reduce .[] as $n ([]; if $n%2==0 then empty else . + [$n] end)

with input

    [0,1,2,3,4,5]

should produce (according to documentation)

     [1,3,5]

but actually produces

    [5]

See [live demo](https://jqplay.org/jq?q=reduce%20.%5B%5D%20as%20%24n%20(%5B%5D%3B%20if%20%24n%252%3D%3D0%20then%20empty%20else%20.%20%2B%20%5B%24n%5D%20end)&j=%5B0%2C1%2C2%2C3%2C4%2C5%5D).

**Comment by pkoppstein** [comment]
I believe you are looking at documentation for a different version of jq than you are using.  In any case, the documentation you are referring to correctly describes the ("correct") behavior of the current version (after jq 1.5):

```
$ jq -nc '[range(0;6)] |reduce .[] as $n ([]; if $n%2==0 then empty else . + [$n] end)'
[1,3,5]
```

Compare the older ("incorrect") behavior of jq 1.5:

```
$ jq1.5 -nc '[range(0;6)] | reduce .[] as $n ([]; if $n%2==0 then empty else . + [$n] end)'
[5]
```

**Comment by frederik-elwert** [comment]
Okay, that explains the difference. Thanks!

**Comment by caramdache** [comment]
I just upgraded to the latest version, but still see the old behaviour. What am I missing ?

```
$ jq -nc '[range(0;6)] |reduce .[] as $n ([]; if $n%2==0 then empty else . + [$n] end)'
[5]
$ jq --version
jq-HEAD-8eff744
```

**Comment by pkoppstein** [comment]
On Dec 11, things changed again -- see 9a4576e7567dd38b91f28592b47eb6dafe0c4332

The documentation should have been changed too, perhaps to say that the behavior arising from the use of `empty` in this context is currently undefined.

In other words, until further notice, it's best not to use `empty` in `reduce`. 

In the particular example, one can simply write `.` instead of `empty` to achieve the `[1,3,5]` result.

**Comment by nicowilliams** [comment]
See #1543.  I guess this is now a docs bug.  Anyways, the problem is that there is no reasonable way to handle `empty` in the reduction state update expression.  Allowing `empty` there to mean "continue with the previous state" requires holding on to a reference for the state, which in turn can make the reduction very slow by forcing many more allocations in the state update expression.

For the example you listed use `.` instead of `empty`.

**Comment by caramdache** [comment]
This does work indeed, thanks.

```
$ jq -nc '[range(0;6)] |reduce .[] as $n ([]; if $n%2==0 then . else . + [$n] end)'
```
