### ISSUE TITLE
Bug: process uint64 occurs error

### ISSUE THREAD

**Issue by chenstrace** [stedolan/jq#1487]
[
![image](https://user-images.githubusercontent.com/16367987/30791185-636f1950-a1e3-11e7-9efc-114369c3f0d0.png)
](url)

**Comment by ligh0721** [comment]
<img width="571" alt="jq_bug" src="https://user-images.githubusercontent.com/2642896/30791286-1eb3f1ea-a1e4-11e7-9880-78c1417ebb47.png">

**Comment by pkoppstein** [comment]
This is a well-known issue (or, depending on your point of view, non-issue): see e.g. the jq FAQ https://github.com/stedolan/jq/wiki/FAQ; Issue #369; etc. (E.g. Google: jq stedolan issue ieee)

@chenstrace -Since #369 is currently open and regarded as the "master" issue for tracking purposes, it would be helpful if you could close #1487.

**Comment by chenstrace** [comment]
ok
