### ISSUE TITLE
Request: colorization should also work on Windows

### ISSUE THREAD

**Issue by sleyzerzon** [stedolan/jq#1494]
When executing `docker-machine inspect` command, instead of the expected highlighted version of JSON piped into jq:

[![enter image description here][1]][1]

I'm seeing the following plain output (in cmd or ConEmu):

[![enter image description here][2]][2]

Not sure what needs to be done to enable proper json highlighting.

This happens on Windows 10 machine on which jq ver. 1.5 was installed via Chocolatey:

[![enter image description here][3]][3]  

  [1]: https://i.stack.imgur.com/UOE1A.png
  [2]: https://i.stack.imgur.com/Qe5oT.png
  [3]: https://i.stack.imgur.com/SBIxZ.png

**Comment by nicowilliams** [comment]
jq does not enable colorized output by default on Windows.  You can force colorization via the `-C` command-line option, though it probably won't work.  I think we just don't know how to colorize output on a Windows console -- hints, links, clue, all welcomed.

**Comment by adoxa** [comment]
Win10 supports control sequences, but it must be explicitly enabled; earlier versions of Windows could use ConEmu (which has an option to support them) or ANSICON. Since ConEmu supports ANSICON's environment variables, something like this should work:

```c
#else // WIN32
  if (GetEnvironmentVariable("ANSICON_VER", NULL, 0) != 0)
    dumpopts |= JV_PRINT_COLOR;
  else {
    HANDLE hCon = GetStdHandle(STD_OUTPUT_HANDLE);
    DWORD mode;
    GetConsoleMode(hCon, &mode);
    mode |= 4/*ENABLE_VIRTUAL_TERMINAL_PROCESSING*/;
    if (SetConsoleMode(hCon, mode)) // fails pre-Win10
      dumpopts |= JV_PRINT_COLOR;
  }
```

**Comment by Simran-B** [comment]
Would be great if the virtual terminal processing could be enabled. It has to be explicitly enabled since the anniversary update 10.0.14393, see https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/15617610--re-enable-enable-virtual-terminal-processing-by

https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#span-idexamplespanspan-idexamplespanexample-of-sgr-terminal-sequences
