### ISSUE TITLE
pipe behavior differs on array iteration vs explicit index

### ISSUE THREAD

**Issue by vanrysss** [stedolan/jq#1498]
I receive this error 

` {"error":"Expected end of stream at char 540"}%
`
when piping output from jq array iteration like so.

`    jq .[] -c <${FILE} | curl -v -d @- https://api.com --header "Content-Type:application/json" --header "$AUTH_HEADER"`

when specifying the element using jq .[0]... it works as expected.

**Comment by wtlangford** [comment]
Are you able to post the contents of $FILE? If not, can you create a
sanitized version that also exhibits the behavior?

**Comment by vanrysss** [comment]
Sure thing, this will exhibit the behavior. I've run it through jsonlint to ensure it's valid.

`[{
        "name": "name",
        "abbreviatedName": "",
        "addresses": [{
            "type": "shipping",
            "recipient": "recipient name",
            "address1": "address",
            "address2": "address2",
            "city": "city",
            "state": "state",
            "zip": "12345",
            "country": "USA"
        }],
        "contacts": [{
            "firstName": "firstname",
            "lastName": "",
            "email": "email@email.org"
        }]
    },
    {
        "name": "name",
        "abbreviatedName": "",
        "addresses": [{
            "type": "shipping",
            "recipient": "recipient",
            "address1": "address1",
            "address2": "address2",
            "city": "city",
            "state": "state",
            "zip": "12345",
            "country": "USA"
        }],
        "contacts": [{
            "firstName": "firstname",
            "lastName": "",
            "email": "email@email..org"
        }]
    }
]`

**Comment by pkoppstein** [comment]
Using `${FILE}` without double-quotation marks (`"$FILE"` should be sufficient) is asking for trouble.  It would probably be better to put the JSON into a file.

In any case, I can confirm that using jq 1.5 or the current "master" version (jq-1.5rc2-245-g7b81a83), running either `jq .[]` or `jq -c .[]` with the given input works flawlessly, even if the input is given without any newlines at all.

**Comment by nicowilliams** [comment]
You *really* have to mind shell quoting!  Use `jq '.[]'`, *not* `jq .[]`!

**Comment by pkoppstein** [comment]
@nicowilliams wrote:

> You really have to mind shell quoting! 

`jq .[]` works fine at the Windows console, and with sh, csh, fish, and bash (tested with GNU bash version 3.2.57 and 4.4.12), so forgive me for getting into bad habits :-)

Needless to say, I'm glad to see you're back in the swing of things here in jq-land.  As it's been over two years since jq 1.5 was released, please forgive me for asking you to make getting a new release out very soon a top priority, or even THE top priority.

In my view, if there is any issue which might warrant a delay, it is the one that I believe uniquely deserves your attention:

https://github.com/stedolan/jq/issues/1534

I say this first become the bug was introduced relatively recently, second because it has caused considerable consternation, and third because I believe you are most likely to be able to fix it
properly.

Thank you!

**Comment by nicowilliams** [comment]
@pkoppstein I'm aware, thanks.
