### ISSUE TITLE
No output with if-then-else

### ISSUE THREAD

**Issue by shadycuz** [stedolan/jq#1513]
Using this data structure.
```
{
    "Vpcs": [
        {
            "Tags": [
                {
                    "Value": "staging",
                    "Key": "Env"
                }
            ]
        }
    ]
}
```

and this query

```
if .Vpcs[].Tags[] | select(.Value =="staging") then "staging" else "why no output" end
```

outputs "staging" when .Value =="staging" but output is "blank" when not found.  Tried on my desktop and in jqplay. Same thing.

**Comment by pkoppstein** [comment]
Welcome to "empty"!

You evidently want something like:

    (select(.Value =="staging") | "staging") // "why no output"

There are many other ways to achieve the semantics you want, e.g. if your jq has `isempty`, you could test whether the stream produced by the `select` is empty.

**Comment by shadycuz** [comment]
@pkoppstein What I want is something along the lines of 

```
if .Vpcs[].Tags[] | select(.Value =="staging") then .Vpcs[].VpcId else "false" end
```

I just haven't included the entire data structure in the above. Should the if still work? because it doesn't and I couldn't get your example to work.

**Comment by shadycuz** [comment]
For example this 
```
if .Vpcs[].Tags[] | select(.Value =="staging") then "one" elif .Vpcs[].Tags[] | select(.Value !="staging") then "two" else "???" end
```
should return two with this input
```
{
    "Vpcs": [
        {
            "Tags": [
                {
                    "Value": "stasdsging",
                    "Key": "Env"
                }
            ]
        }
    ]
}
```

but it doesn't, obviously if is broken

**Comment by shadycuz** [comment]
@pkoppstein This worked for me in the else
```
aws ec2 describe-vpcs | jq -r '(if .Vpcs[].Tags[] | select(.Value =="prod") then .Vpcs[].VpcId else "???" end) // "false"'
```

**Comment by pkoppstein** [comment]
(1) Rest assured, jq's "if" is not broken.  It is important to understand that jq is stream-oriented, and that if the CONDITION in `if CONDITION then ... else ... end` evaluates to the empty stream, then the entire if/then/else/end expression also evaluates to the empty stream.  That is why you you should become familiar with `//`.

(2) With jq version 1.4 or higher, and with your original JSON in a file named input.json, and with the following in program.jq:

    .Vpcs[].Tags[]
    | (select(.Value =="staging") | "staging") // "why no output"

the invocation:  jq -f program.jq input.json
yields:

    "staging"

And if the input is modified so that "Value" has some other value, the same invocation produces:

    "why no output"

(3) If you have jq 1.5, then to achieve your revised goal, consider:

    if isempty(.Vpcs[].Tags[] | select(.Value =="staging")) then false else .Vpcs[].VpcId end

This is probably not what you REALLY want, but it does correspond closely to what you've indicated you want.

(4) Please ask any further usage questions on stackoverflow.com using the `jq` tag.
