### ISSUE TITLE
Unbuffered input mode

### ISSUE THREAD

**Issue by bendem** [stedolan/jq#1530]
I'm interested in using jq to filter infinite streams (mainly for monitoring purposes). I have a program that ouptputs json objects and I want to insert jq in the pipeline between its output and the process it's sent to. Sadly, it seems like jq will not start parsing objects until it encounters a \n in the stream.
Is there a way to add an unbuffered input mode in which the filter is applied as soon as an object is read and output the result directly instead of waiting for a \n or the end of the stream.

Reproduction step:
```bash
$ cat <(echo -n "{}\n{}{}{}{}") /dev/stdin | jq --unbuffered
{}<hangs><ctrl-d>
{}
{}
{}
{}
```

**Comment by pkoppstein** [comment]
Here is a workaround using stdbuf or in my case gstdbuf: add this to the pipeline

    gstdbuf -o0 gawk 'BEGIN{ORS=RS="}"}{print $0 "\n"}'

**Comment by bendem** [comment]
Thanks, that works (the GNU syntax is `stdbuf -o0`), I'd still like to have it built into jq.

**Comment by pkoppstein** [comment]
@bendem - I suspect the maintainers mught decide that the pros of changing the implementation do not outweigh the cons, but in any case, I think the change you would like should be regarded as low priority because the standards and de-facto standards for streaming JSON require some sort of separator. E.g. JSON Lines is quite sensible. Could the generator of your stream not be made to conform to some such standard?

**Comment by bendem** [comment]
I mean, from my point of view, it's very easy to parse json without separators. The only values that could pose problems are scalars (numbers and booleans), and it can just be specified that the feature only works with objects and arrays.

Now sure, I understand it isn't high priority, just wanted to get it out there as I don't think that pattern is *that* uncommon or *that* hard to implement.

**Comment by pkoppstein** [comment]
> it's very easy to parse json without separators.

Yes, jq does that.  The issue that I am addressing is whether supporting unbuffered input (-i0) should be a high-priority enhancement for jq. I think not, in part because such an option might encourage deviation from sensible standards, the point being that sources of JSON streams should allow consumers to buffer their inputs for efficiency.

I would agree that the current jq documentation about this needs fixing.

**Comment by nicowilliams** [comment]
@bendem jq _necessarily_ deals in fully parsed JSON texts.  HOWEVER, you can use the `--stream` option to parse in a streaming way, though the way that works is very different to what you are used to.

**Comment by bendem** [comment]
@nicowilliams, I'd be happy to work with `--stream` if it solved the problem I'm facing, but it doesn't change anything. jq still hangs until either, its buffer is full, it encounters a new line, or it encounters EOF.

```
cat <(echo -n "{}\n{}{}{}{}") /dev/stdin | jq --unbuffered --stream
[
  [],
  {}
]<hangs>
[
  [],
  {}
]
[
  [],
  {}
]
[
  [],
  {}
]
[
  [],
  {}
]
```

Also, I don't see how `{}\n` ist fully parsed and `{}` isn't. Jq interprets both exactly in the same way once forced to do so (by sending EOF).

**Comment by nicowilliams** [comment]
You're probably suffering from #1534.
