### ISSUE TITLE
Is there a way to extend functions library? Possible binding to external sources

### ISSUE THREAD

**Issue by OnkelTem** [stedolan/jq#1535]
Probably my request is a bit unusual or may sound even stupid - sorry then. Imagine a system which  processes and provides some data in json format. If we had a way to write custom functions to interacting with that system, we could write something like:

```
jq -n 'get_data_from_the_system(params)|...jq code...|save_data_to_the_system(params)'
```
or
```
jq '...jq code...|load_additional_data_from_the_system(params)|...jq code...|save_data_to_the_system(para,s)' < source_data
```

Ideas?

**Comment by pkoppstein** [comment]
> Ideas?

Yes. Read the [jq manual](https://stedolan.github.io/jq/manual), and in particular the section on "Defining Functions".

For future reference, please ask usage questions at stackoverflow.com with the [`jq` tag](https://stackoverflow.com/questions/tagged/jq).

**Comment by OnkelTem** [comment]
@pkoppstein Before creating my request I search the queue and found similar question and the same answer. However I don't see how do they relate to my question?

**Comment by pkoppstein** [comment]
@OnkelTem - If you understand how to define functions and modules in jq, then you should be able to formulate your question or proposal more precisely.  If you have a specific usage question, please post it to stackoverflow.com with the jq tag (https://stackoverflow.com/questions/tagged/jq). In any case, whether you post a followup here or there, I would suggest you abide by the recommendations at http://stackoverflow.com/help/mcve . Thank you.

**Comment by OnkelTem** [comment]
@pkoppstein It seems to me that misunderstanding is progressing. I asked - is there a way to extend the set of built-in functions with some custom functions. Isn't it clear from my question? I was talking about connecting to external databases and systems. I don't understand how would 'def' something on jq pseudo language solves this?

**Comment by pkoppstein** [comment]
@onkeltem - Your original question didn't mention "external databases and systems", but since you mention them, the answer I believe will depend on whether or not you want to use jq-as-is,

I think the basic answer to your question is that jq itself is currently confined to reading from files, file handles, STDIN, the command-line, and environment variables.  All this is clear from the jq manual.  However, you find it useful to know about the work that has been done to integrate jq with languages such as Python, Ruby, Node.js; see https://github.com/stedolan/jq/wiki/FAQ#language-bindings

If you want to extend jq with C/C++ code, you may find the information on the wiki (https://github.com/stedolan/jq/wiki) useful, e.g. `Advanced Topics` and the various pages starting with "C API".

**Comment by OnkelTem** [comment]
Oh, thank you very much. Seems like I've missed this information somehow. I only used Manual.
