### ISSUE TITLE
How to validate a JSON string with jq?

### ISSUE THREAD

**Issue by cnfn** [stedolan/jq#1539]
`jq` is very powerful and I like it very much. But I confused when validate a JSON string with it.
`123` and `{"a:1` are invalid JSON, but they result are different. We can't validate it by `jq` output or exit value.

So, is there any way to validate a JSON string? 

```sh
$ echo '123' | jq .
123
$ echo $?
0

$ echo '{"a": 1' | jq .     // will not output anything
$ echo $?
0

$ echo '{"a":1}' | jq .
{
  "a": 1
}
```

**Comment by pkoppstein** [comment]
1. You have uncovered a (by now well-known) bug that was introduced relatively recently.

2. In any case, jq is not always reliable as a JSON validator, which is not to say it isn't useful as such in practice.

3.  If you just want to test the validity of a purported JSON entity, then I would suggest as a workaround that you use `type` as the filter instead of `.`.  

For example, using the buggy version of jq:

     $ echo '{"a": 1' | jq .
     $ echo '{"a": 1' | jq type
     $

That is, instead of a jq type, the result is the empty stream.  So, by testing both the return code and the emitted value(s), one can get a more accurate picture of the validity of the input.

**Comment by cnfn** [comment]
@pkoppstein 
Thank you very much~
`jq type` will be my solution.  It likes [JSON_TYPE function](https://dev.mysql.com/doc/refman/5.7/en/json-attribute-functions.html#function_json-type) of MySQL 5.7

**Comment by felipecrs** [comment]
Duplicate of https://github.com/stedolan/jq/issues/1637

**Comment by dginovker** [comment]
For future Googler's:

```
cat my.json | jq type
```

**Comment by specious** [comment]
If you'd like it to print nothing unless there's a parsing error:

```
cat file.json | jq type 1>/dev/null
```
