### ISSUE TITLE
One error about  symbol@

### ISSUE THREAD

**Issue by Giggledefy** [stedolan/jq#1548]
我有一个JSON串，其中一个key值是"@id" 我用.如无论如何也取不到【 I have one JSON , one of its key is "@id"】：

`{"job":{"@id":"FDF560BBAA8A00BBC04CD00406203FB9","@status":"queue","@queue-time":"2017/12/07 21:37:08"},"message":null}`

**Comment by Giggledefy** [comment]
[user@balala ~]$ a=`thatJSON`

**Comment by pkoppstein** [comment]
In your shell -
1. Use double-quotes around $a
2. Use single-quotes around the jq query

For key names with special characters, one cannot use the abbreviated form. If you are using a recent version of jq, you can use double-quotes, as in .jq.job.”@id”

Otherwise, you will have to use the unabbreviated syntax, with pipe separation, as in

    .jq.job | .[“@id”]

p.s. in future, please ask usage questions at stackoverflow.com with the jq tag

**Comment by Giggledefy** [comment]
用了你的方法也没有解决。不过我突然发现可以用 `echo $a|tr -d "@"|jq .job.id`  来解决这个事情
