### ISSUE TITLE
Update json values with shell script

### ISSUE THREAD

**Issue by NatrajL** [stedolan/jq#1552]
I have a json as below

`{
  "AWSTemplateFormatVersion": "1.0",
  "Description": "AWS CF Template",
  "Parameters": {},
  "Mappings": {
    "12345678": {
      "Description": "Test1",
      "us-east-1": {
        "VPC": "abcd",
        "AmiId": "ami-6869aa05"
      },
      "eu-west-1": {
        "VPC": "Test2",
        "AmiId": "ami-f9dd458a"
      }
    }
  }
}`

I want to update the AmiId field only if it present as i will be looping over multiple json files in same directory, iam using the below script to do that but the problem is if the field is not present the jq command is appending the json.

Is there anyway i can only update if the "AmiId" field is present and skip if its not.

`#!/bin/bash -x

function get_regional_image() {
  region="$1"
  [[ -z $region ]] && { echo "${FUNCNAME}(): region not specified"; exit 1; }
  aws ec2 describe-images --owners amazon --filters 'Name=name,Values=amzn-ami-hvm-????.??.?.x86_64-gp2' --region $region 'Name=state,Values=available' | jq -r '.Images | sort_by(.CreationDate) | last(.[]).ImageId'
}

regions=( us-east-1 eu-west-1 )
for i in "${regions[@]}"
do
  ami="$(get_regional_image $i)"
  for j in `find . -name "*.json"`
  do
   export  region="$i"
   jq -r ".Mappings.\"12345678\".\"${region}\".AmiId=\"$ami\"" $j > $j.tmp && mv $j.tmp $j
  done
done`

**Comment by pkoppstein** [comment]
0. Thanks for your interest in jq!

1. We strongly recommend that you use --arg or --argjson to pass in shell parameters, rather than using shell variables directly in the jq program.  The following illustrates how this could be done in your case:

    jq -r --arg ami "$ami" --arg region "$region" "$PROGRAM" "$j"

where "$PROGRAM" is now a fixed jq expression, such as shown in (2) below.

2.  If you want to update something conditionally, then you'll need to say so, e.g. assuming that you are adopting the strategy mentioned in (1):

```
if (.Mappings."12345678" | .[$region]) | has("AmiId") 
then (.Mappings."12345678" | .[$region] | .AmiId) = $ami
else .
end
```


3. In future, please ask usage questions at stackoverflow.com with the `jq` tag: 
 https://stackoverflow.com/questions/tagged/jq

**Comment by NatrajL** [comment]
Hi @pkoppstein ,

Thank you very much for your reply, I will make note of the stack overflow link for future questions, since we started here i will continue an follow up here please.

I'm getting jq compile errors with the below script , can you please advise what iam doing wrong.

`#!/bin/bash -x

function get_regional_image() {
  region="$1"
  [[ -z $region ]] && { echo "${FUNCNAME}(): region not specified"; exit 1; }
  aws ec2 describe-images --owners amazon --filters 'Name=name,Values=amzn-ami-hvm-????.??.?.x86_64-gp2' --region $region 'Name=state,Values=available' | jq -r '.Images | sort_by(.CreationDate) | last(.[]).ImageId'
}

regions=( us-east-1 eu-west-1 )
for i in "${regions[@]}"
do
  ami="$(get_regional_image $i)"
  for j in `find . -name "*.json"`
  do
   export  region="$i"
   PROGRAM="if (.Mappings."12345678" | .[$region]) | has("AmiId") \
then (.Mappings."12345678" | ."[$region]" | .AmiId) = $ami \
else . \
end"
  jq -r --arg ami "$ami" --arg region "$region" "$PROGRAM" "$j"
  done
done`

**Comment by pkoppstein** [comment]
1. When having difficulties with shell scripts, it is often a good idea to move stuff out of the script, if only during debugging.  In the present case, you could put the PROGRAM into a file, test it independently, test it in the context of your script, etc, etc.  (If you do this, you would of course invoke jq with the -f option.)

2. The problem that I can see is that you have improperly defined PROGRAM.  Since PROGRAM includes double-quotes, the simplest would be to enclose the text of the program in single quotes.  bash is quite nice that way.

3. We are glad to help with jq-related questions, but when you start to run into shell usage issues, this is not really the right place.  That's another reason to post usage questions on stackoverflow.com --  you can specify multiple tags there (e.g. `jq`, `bash`, `aws`), and you are more likely to find the people who can help resolve all the issues.

4. For future reference, when including code samples (on github or stackoverflow.com), please format the samples properly.  Here, the `<>` editing icon can be helpful in that regard; on stackoverflow there's a similar editing icon.

4. When you're done here, please don't forget to "CLOSE" this issue. Thanks.

**Comment by NatrajL** [comment]
Hi @pkoppstein ,

Thanks for your help, that worked.
