### ISSUE TITLE
add object to dynamic key

### ISSUE THREAD

**Issue by gdbtek** [stedolan/jq#1591]
I'm looking to build object using jq and add object key to dynamic key and I could not figure out. Here is my sample script:

```
#!/bin/bash -e

environments=('development' 'stage' 'production')
regions=('us-east-1' 'us-west-2')

tree='{}'

for environment in "${environments[@]}"
do
    echo "${environment}"
    # Or do something else with environment

    tree="$(jq --arg jqEnvironment "${environment}" '. | .[$jqEnvironment] = {}' <<< "${tree}")"

    for region in "${regions[@]}"
    do
        echo "${region}"
        # Or do something with region

        tree="$(jq --arg jqEnvironment "${environment}" --arg jqRegion "${region}" '. | .[$jqEnvironment] | .[$jqRegion] = {}' <<< "${tree}")"
    done
done

jq . <<< "${tree}"
```

Actual outputs
```
{
  "us-west-2": {}
}
```

But what I want is this outputs

```
{
  "development": {
    "us-east-1": {},
    "us-west-2": {}
  },
  "stage": {
    "us-east-1": {},
    "us-west-2": {}
  },
  "production": {
    "us-east-1": {},
    "us-west-2": {}
  }
}
```

I could not figure out, please help!

**Comment by pkoppstein** [comment]
1. Thank you for your interest in jq, which is well-suited to handling the problem you describe.
2. Since you have posted the same question on stackoverflow.com, an answer has been posted there, as stackoverflow is very well designed for such usage questions. See https://stackoverflow.com/questions/48512598/add-object-to-dynamic-key-using-jq
3. In future, please post usage questions on stackoverflow.com rather than here.

**Comment by gdbtek** [comment]
Thanks @pkoppstein for your helps. It's very helpful. I added some comments on your solution and I hope you have a long form solution that I can use. Your short-form solution is so cool though.
