### ISSUE TITLE
Cannot index object with number

### ISSUE THREAD

**Issue by gaia** [stedolan/jq#1613]
`curl 'url' | jq '.[0]'`
https://pastebin.com/5i5VDBYz 
returns
`jq: error (at <stdin>:0): Cannot index object with number`
on Linux box.example.com 4.14.17-x86_64 (Ubuntu 16.04)

**Comment by pkoppstein** [comment]
The JSON at https://pastebin.com/5i5VDBYz is an object, and as the error message says, you "cannot index [an] object with [a] number".  Since you haven't indicated what you are trying to do, it's hard to know what you intended, but you might like to lookup `.[]` in the jq manual.

For future reference, please ask usage questions at stackoverflow.com using the [jq tag](https://stackoverflow.com/questions/tagged/jq).  See also the "minimal complete verifiable example" guidelines at http://stackoverflow.com/help/mcve

**Comment by gaia** [comment]
thx. i am trying to extract a single element from the JSON.

**Comment by pkoppstein** [comment]
If you cannot figure it out after reading the (very brief)[ tutorial](https://stedolan.github.io/jq/tutorial/) and/or scanning the [manual](https://stedolan.github.io/jq/manual/v1.5), I'd suggest posting a question at stackoverflow.com with the jq tag, following the previously-mentioned mcve guidelines.

**Comment by rbrisita** [comment]
Here is one approach for anyone finding this on their search for an answer:

echo '[{"name":"joe"}, {"name":"john"}, {"name":"jose"}]' | jq '[.[] | .name] | .[1]'

This will wrap the processed data in an array from which you can index a particular value.

**Comment by ayehia2000** [comment]
> Here is one approach for anyone finding this on their search for an answer:
> 
> echo '[{"name":"joe"}, {"name":"john"}, {"name":"jose"}]' | jq '[.[] | .name] | .[1]'
> 
> This will wrap the processed data in an array from which you can index a particular value.

Thank you so much

**Comment by alvaromuir** [comment]
> echo '[{"name":"joe"}, {"name":"john"}, {"name":"jose"}]' | jq '[.[] ] | .[0]'
will bring back the first element of any json doc AFAIK
