### ISSUE TITLE
included JSON file treated as stream instead of valid JSON (jq 1.6rc1)

### ISSUE THREAD

**Issue by dkrieger** [stedolan/jq#1622]
`include "./jq/json-file" as $file;` treats json-file.json as a stream -- just like slurpfile, it provides an array of top-level JSON entities found. JSON streams are not valid JSON files, so this seems incorrect.

If the goal is to permit inclusion of streams, perhaps the following can allow that while better adhering to file extension semantics:

- no extension? parse as valid JSON
- '.json' extension? parse as valid JSON
- non '.json' extension? parse as JSON stream

**Comment by nicowilliams** [comment]
- `$name` can only bind a single value.
 - jq doesn't know about file type extensions
 - jq has always supported whitespace-delimited JSON text "streams"
 - considering all of the above, "slurp" semantics are the only reasonable semantics
 - users can deal

```
import "..." as $foo;

$foo[0] as $foo |
    # here $foo refers to the first JSON text (parsed) in the imported file
    ...
```

**Comment by dkrieger** [comment]
> jq doesn't know about file type extensions

`import "bar" as $foo;` references "bar.json". only files with '.json' extension can be included with this directive. This somewhat miscommunicates that^ fact.

> "slurp" semantics are the only reasonable semantics

That's perfectly reasonable. Can we follow slurpfile semantics even further and not do any magic extension concatenating? Simplify code + improve semantics = win.

> users can deal

Hey I'll take what I can get, I love this tool. I certainly wouldn't consider this a high priority issue, and I don't mean to suggest that it is.

**Comment by nicowilliams** [comment]
Ultimately, the fact that `$name` can bind only one value, not a stream of values, there's nothing we can do differently here.  Perhaps some day we could introduce an `import ... as def <name>;` such that `<name>` is like a function that outputs the stream of values in the file -- I don't see what else could be done.

**Comment by dkrieger** [comment]
I get what you mean, we're in agreement about that at this point. The idea to introduce `import . . . as as def <name>;` was not on my radar, but I like it. What do you think about allowing the relative path to reference files not ending in ".json"?

**Comment by adriancuadrado** [comment]
@nicowilliams Any progress on introducing `import ... as def <name>;`? You said you don't know what else could be done here. May I suggest to always take only the first value and just throw some kind of error when more than one values are found in a json file? json files are meant to have a single value, be it an object, array or whatever. The only way to have multiple values is to wrap them in an array. I don't understand why you assume there could be multiple values in a json file in the first place...

This is what happens when you attempt to have multiple values in a single json file:
![image](https://user-images.githubusercontent.com/29214635/212446037-21332e30-2a4e-4703-b327-9b95457f219d.png)
As you can see, the file is considered to have an invalid json. I insist that I don't understand why would a json file have many values like you describe.
