### ISSUE TITLE
Keys with Hyphens run a bug

### ISSUE THREAD

**Issue by doling0** [stedolan/jq#1695]
```
foo.json
{
  "abc": {
    "abc-aa": {
      "name": "kevin",
      "age": 19
    }
  }
}
```

when use jq parse:
```
# jq .abc.abc-aa.name foo.json
jq: error: aa/0 is not defined at <top-level>, line 1:
.abc.abc-aa.name         
jq: 1 compile error
```

**Comment by pkoppstein** [comment]
This topic is covered in the manual, the jq FAQ (
https://github.com/stedolan/jq/wiki/FAQ), this website, stackoverflow.com, and elsewhere.

See e.g. #1694

**Comment by pkoppstein** [comment]
@leonid-s-usov - Thanks for the helpful comment.

The FAQ Q that was being referred to specifically was:

    𝑸: What alternatives are there to .["key"] for accessing the value of a key?

Since it was evidently being missed, and since there does not seem to be a satisfactory way to index the questions, I added another Q with additional and hopefully more searchable keywords:

    𝑸: How can I access the value of a key with hyphens or other special characters in it?

**Comment by doling0** [comment]
got it,thank you

**Comment by hyperpallium** [comment]
Ideally, such errors would trigger a helpful error message. This does happen for some cases, but it's awkward to detect with jq's yacc/bison parser, and of course some can't be detected (because they happen to be valid syntax for a different construct).

BTW JSON also had this problem of special characters, with this solution of quotation. From your example:

    "abc-aa": {
