### ISSUE TITLE
jq parses invalid JSON file without error

### ISSUE THREAD

**Issue by jwkblades** [stedolan/jq#1705]
Given the JSON input file (two top-level JSON objects which aren't contained within an array or other object):

```
{
    "test": "value"
}
{
    "another object": 42,
    "breakfast": [
        "waffles",
        "coffee",
        "eggs"
    ]
}
```

JQ runs through the file as if there is no issue:

```
▶jq . example.json
{
  "test": "value"
}
{
  "another object": 42,
  "breakfast": [
    "waffles",
    "coffee",
    "eggs"
  ]
}

▶jq .breakfast example.json
null
[
  "waffles",
  "coffee",
  "eggs"
]

▶echo $?
0
```

However, this should be a parsing error based on the [JSON specification](http://json.org/).

In fact, Chrome gives a JavaScript error if you attempt to parse the same JSON value (without nice whitespace so it is a one-liner):

```
JSON.parse('{"test": "value"} {"another object": 42,"breakfast": ["waffles","coffee","eggs"]}');
VM53:1 Uncaught SyntaxError: Unexpected token { in JSON at position 18
    at JSON.parse (<anonymous>)
    at <anonymous>:1:6
```

**Comment by pkoppstein** [comment]
@jwkblades - jq expects its input to be a *stream* of JSON texts, so what you have characterized as a bug is in fact one of the most important features of jq.

If you find the jq manual to be deficient on this point, then you might like to take a look at
["A Stream-Oriented Introduction to jq"
](https://github.com/pkoppstein/jq/wiki/A-Stream-oriented-Introduction-to-jq)

**Comment by jwkblades** [comment]
So, the manpage is sufficient in that it takes a stream; but the fact that it also has a `--stream` option to tell jq that it is taking a stream and allowing one or more files for input seems unintuitive to me. After all, passing in a JSON file, I would expect that JSON (read from a single file) to be valid and not a stream of value (in the case of one or more input files, I would expect each one to be a valid single value - whatever that winds up being).

If it is decided that this isn't a bug, or is a "won't fix" scenario; I would love to see an option to tell jq it is not to work on a stream, but instead error out if it finds multiple JSON blobs being fed into it.

**Comment by pkoppstein** [comment]
@jwkblades - The `--stream` option enables the streaming parser, which is a whole different kettle of fish -- one might even say an orthogonal kettle of fish.  (The `--stream` option, on the other hand, is closely related to the `tostream` filter.)

The creator and maintainers of jq are loathe to add new options.  Since it's easy enough to write a jq filter for counting the number of JSON texts in the input stream (*) (and therefore to raise an error if the stream does not contain the expected number of JSON texts), this particular proposed option does seem fairly pointless to me, quite apart from the fact that there are other JSON processors out there that would do the job.

(*) Consider e.g. the following, used in conjunction with the -n option:

    def count(s): reduce s as $i(0; .+1);
    count(inputs)

**Comment by jwkblades** [comment]
@pkoppstein Thanks for the assist with the filter, I think we can likely implement that as a check to ensure "valid" (from our perspective) JSON before doing further parsing across the board for our situation.

I am going to go ahead and close this. The solution for future people looking at similar issues is to implement a check before parsing the data and ensure that `count(inputs)` returns 1 (or whatever number you are expecting):

```
def count(s): reduce s as $i(0; .+1);
count(inputs)
```

Usage (example): `jq -n 'def count(s): reduce s as $i(0; .+1); count(inputs)` inputFile.json`

Thank you for your time!
