### ISSUE TITLE
Simple/elegant way of testing if an element belongs to an array?

### ISSUE THREAD

**Issue by ncfavier** [stedolan/jq#1708]
So say my input is a bunch of objects, each with an "extension" key, and i want to filter these objects to keep only those which have their extension in some list. I need to test if `.extension` belongs to some fixed array.

What is the simplest way to do this? I am aware of the following two ways:

```jq
select(.extension as $ext | [".jpg", ".png"] | index($ext))
```
This is not very elegant since I am forced to use a variable. Is there a way to avoid it?

```jq
select(.extension == (".jpg", ".png"))
```
This works, but if an extension appears twice in the list it will duplicate any inputs with that extension.

I am not mentioning `contains` and `inside` because they do something completely different. And `has` and `in` aren't really fit either since the extension list would have to be an object.

**Comment by pkoppstein** [comment]
@naim42 - You raise an interesting point, but your example does not illustrate it,
because in jq, an object's keys can each be associated with only one (possibly compound) value.

So let's devise a more relevant example:

    {a:0, files: ["a.jpg", "b.jpg"] }
    {a:1, files: ["a.png"]}

To keep the file extension theme, let's define:

    def extension: capture("\\.(?<x>[^.]*)$").x;

Now to solve the problem declaratively, without recourse to jq variables, we could write:

    select( any(.files[]|extension; . == "jpg" or . == "png") )

Of course, this is not so convenient when multiple alternatives exist, so let's consider some alternatives.

One would be to define index/2 so that it ignores its input:

    def index(item; array): array|index(item);

Then we can simply write:

    select( index(.; [".jpg", ".png"]) )

Another approach would be to define a filter for checking whether two arrays have a common
element:

    def intersects($b): any(.[]; . as $x | any( $b[]; . == $x) ) ;

Using the above example and this last definition, we could then write:

    select( .files | map(extension) | intersects( ["jpg","png"] ) )

**Comment by naim42** [comment]
Thanks for your answer.

> @naim42 - You raise an interesting point, but your example does not illustrate it,
because in jq, an object's keys can each be associated with only one (possibly compound) value.

I know this is how JSON works, but I'm not sure how that applies to my question. To clarify, my input would look something like this:

```json
{"a": 0, "extension": ".jpg"}
{"a": 1, "extension": ".png"}
{"a": 2, "extension": ".gif"}
```

My intent is, given the list of extensions `[".jpg", ".png"]`, to keep only the objects whose `extension` key has a value inside that list (here, the first two).

You seem to have answered a different question, but if I extract the relevant parts, you are suggesting the following:

```jq
select(.extension == ".jpg" or .extension == ".png")
```

This is fine, so long as the list is static. What if I want the list to be part of my input? Consider `jq --argjson allowedExtensions '[".jpg", ".png"]' ...`.

Your second example suggests defining a function. Keep in mind that I'm asking for a *simple* way to achieve this — as one would expect from any programming language that deals with arrays, let alone one as powerful as jq.

I have come up with a third way:

```jq
select(any(.extension == $allowedExtensions[]; .))
```

This doesn't have the duplication problem, but is still a bit convoluted.

**Comment by naim42** [comment]
Thanks for your answer.

If the allowed extensions list is `[".tar.gz", ".gifv"]`, your solution will allow `.gif` and `.tar` to pass through, because of how `inside` and `contain` work.

**Comment by pkoppstein** [comment]
@naim42 wrote:

> My intent is, given the list of extensions [".jpg", ".png"], to keep only the objects whose extension key has a value inside that list (here, the first two).

For a stream of objects such as shown, your original solution (adapted for an array) works and seems simple enough to me (though for long arrays it would evidently be inefficient):

    select(.extension == [".jpg", ".png"][])

If there's any chance that the array might contain duplicates, then you might wish to use `unique`, e.g.

    select(.extension == ([".jpg", ".png"]|unique[]))

Also, I appreciate that you're looking for a "def-free" solution, but it might be worth pointing out that jq supports the automatic inclusion of a "standard library" in the form of a file named .jq in the $HOME directory.   

Unfortunately, using ~/.jq as a "standard library" conflicts with its use as a directory, so for ease of reference, let me mention that if your standard library is in ~/.jq/jq.jq then you can simply include it by including `include jq;`.
