### ISSUE TITLE
jq crash

### ISSUE THREAD

**Issue by rdm** [stedolan/jq#1719]
**Describe the bug**
I encountered a bug where gsub using regular expressions which involved backslashes and single quotes was not working properly.

When working on a finding a relatively simple example of the problem, I found that jq would crash.

**To Reproduce**
To reproduce this problem create two files:

bin/flawed:

```
  #!/usr/bin/jq -rf
  
  gsub("\\\\";"\\\\")| gsub("\n";"\\n")| gsub("'";"\\'")| sub("^";"'")| sub("$";"'")
```

flaw-example:

```
  "Alamos's what’s Babi’s Babi’s"
```

Then run `cat flaw-example | bin/flawed`

**Expected behavior**
If jq where working properly, this would produce the result:

```
  'Alamos\'s what\’s Babi\’s Babi\’s'
```
**Environment**

  $ uname -a
  Linux ip-172-31-93-220 4.4.0-1049-aws #58-Ubuntu SMP Fri Jan 12 23:17:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
  $ jq --version
  jq-1.6rc1-16-g341a5fc-dirty

**Additional context**
I'm using jq to build sql statements for use in mysql. I can work around this problem by using the @sh filter and then post-processing using some other program. But I would prefer that jq work correctly.

**Comment by pkoppstein** [comment]
Thanks for taking the time to report the issue so carefully.

Although I can reproduce the problem using jq 1.5, I've not been
able to do so on a Mac using the current "master" version.

Since there is a small discrepancy between your jq code
and the expected output, I've tried several variations,
including this one:

```
gsub("\\\\";"\\\\")
| gsub("\n";"\\n")
| gsub("'"; "\\'")
| gsub("’"; "\\'")
| sub("^";"'")
| sub("$";"'")

```

With your input and incantation, this last produces (as expected):

`'Alamos\'s what\'s Babi\'s Babi\'s'
`

After verifying that you can reproduce the bug using a recent
version of jq from "master", perhaps you could try to
pinpoint the problem more precisely, e.g. by commenting
out lines successively, and by adding `debug` statements.

**Comment by rdm** [comment]
Hmm... I don't see what you changed, other than the addition of newlines.

That said, you are right, and I should have refined that test case further. A simple

```
  #!/usr/bin/jq -rf
  
  sub("$";"'")
```

dumps core with the linux version I was using (which I though was the most recent version of the master branch of jq)

That said... 

I was using /usr/bin/jq (jq-1.5-1-a5b5cbe) and the jq from the master branch was /usr/local/bin/jq.

Replacing the user would have fixed this problem.

(sorry about the noise)
