### ISSUE TITLE
Got "FATAL: kernel too old" by Running

### ISSUE THREAD

**Issue by benjamin-bin-shen** [stedolan/jq#1753]
**Describe the bug**
download jq-linux64

**To Reproduce**
run it in RHEL 7
get the following:
[root@sowlx212 ~]# echo '["a","b","c","d","e"]' | jq '.[2:4]'
FATAL: kernel too old

**Expected behavior**
NA

**Environment (please complete the following information):**
 - OS and Version: 
[root@sowlx212 ~]# lsb_release -d
Description:    Red Hat Enterprise Linux AS release 4 (Nahant Update 7)
[root@sowlx212 ~]# uname -a
Linux sowlx212 2.6.9-78.0.8.ELsmp #1 SMP Wed Nov 5 07:14:58 EST 2008 x86_64 x86_64 x86_64 GNU/Linux
 - jq version 1.5

**Additional context**
NA

**Comment by wtlangford** [comment]
How did you get your `jq` binary? That error typically indicates that the statically linked glibc doesn't like your kernel version. The binary releases we produce are statically linked, so they can be easily used.

I'll point out that RHEL7 is based off of linux kernel 3.10+. RHEL hasn't been based on 2.6.9 since RHEL4, which matches your `lsb_release -d` output (Nahant was RHEL4's codename). The way RHEL handles updates like this involves leaving the base kernel version alone and backporting features.

If possible, try install jq using your package manager (which will get you a dynamically-linked version). Otherwise, I'd recommend compiling jq from source, which should also create a dynamically-linked version.

**Comment by nicowilliams** [comment]
What @wtlangford said.  The binaries we provide are a courtesy.  If they don't work for you, or if we don't provide a binary for your choice of platform, then you must either install from your operating system's package repository, from something like Brew, or build from source.

**Comment by amauri912** [comment]
This thread is consistent, not a bug. I had the same problem described here fixed after downloading an older version for older kernel.

**Comment by wmealing** [comment]
Just a heads up, this is NOT RHEL 7 that the original reporter is running. They are running that on RHEL 4.
