### ISSUE TITLE
Not able to output the merged file to a new json file

### ISSUE THREAD

**Issue by dnr1503** [stedolan/jq#1894]
I used the below command to merge 2 json files using windows command prompt : 

jq -s '.[0] * .[1]' file1.json file2.json > Output.json

But I am not getting the output in json ascii encode. While parsing I get an error :
"Failed to parse template: Error parsing JSON: invalid character 'ÿ' looking for beginning of value"

Please let me know how can I output to json file to fix this error.

**Comment by pkoppstein** [comment]
@dnr1503 - It looks like you've already posted this question at https://stackoverflow.com/questions/55807612/to-output-the-merged-file-into-a-json-file

That is indeed the appropriate place for usage questions.  

As pointed out in a comment to the question there, you should also provide an example (that is, showing your file1.json and file2.json).  

In summary: please CLOSE this issue here on github, and provide an example at stackoverflow.com.
