### ISSUE TITLE
jq error in OpenSUSE jq 1.6-1.1 but not in 1.5-lp150.1.10 

### ISSUE THREAD

**Issue by mamili2** [stedolan/jq#1904]

**Comment by mamili2** [comment]
in openSuse x86_64 Leap 15.0
Repository         : @System
Name               : jq
Version            : 1.6-1.1
Arch               : x86_64
Anbieter           : openSUSE
Installierte GrÃ¶Ãe : 105,9 KiB
Installiert        : Ja
Status             : aktuell
Quellpaket         : jq-1.6-1.1.src

doing a  
 jq -r  '.status.phase ' fjson.file 
 
the file content is from kubectl get pod name_of_pd -o json > json.file 

brings up the error
jq: execute.c:1071: jq_compile_args: Assertion `jv_get_kind(args) == JV_KIND_ARRAY' failed.

same statement with 
Repository         : openSUSE-Leap-15.0-Oss
Name               : jq
Version            : 1.5-lp150.1.10
Arch               : x86_64
Anbieter           : openSUSE
Installierte Groesse : 93,4 KiB
Installiert        : Ja
Status             : aktuell

works fine

**Comment by mamili2** [comment]
downgrading the jq package isnt realy what i like to do, becuae other package are relying in a specific version (jq 1.6 is needed in some cases)
(sorry for my bad english)

**Comment by nicowilliams** [comment]
@mamili2 can you show us the JSON text?

**Comment by nicowilliams** [comment]
Although this is very strange.  I wonder what commit OpenSUSE's jq 1.6-1.1 is packaged from.  No commit since 1.6, or 1.6 itself, has had that assert at `src/execute.c:1071`.  Also, since the assertion trips in `jq_compile_args()`, that means the jq program never even compiled, let alone ran, but I've no problem compiling that program.

@mamili2 how would I get the source to OpenSUSE's jq pkg?

**Comment by nicowilliams** [comment]
@mamili2 also, does the jq executable from our github release page work for you?

**Comment by mamili2** [comment]
Hello Nico,

sorry fort the late answer. 
The json Text i can’t show you because it is not my private stuff (and i am not allowed to show business related stuff in public). It is generated from ouput of a normal „kubectl get pods –o json“ command. Mayby that helps? 

I did not use your packages, but only the one provided from openSuse Repository (even the downgraded Version is from there).

And sorry again: i do not know how one can get sourcecode to openSuse. 

I did noth try to install packages from other source then official openSuse Repo. 
(right now i am having Fireall problems hier, but i will try to install a 1.6 Version from guithub as soon as possible).

Kind regards, mamili2

**Comment by nicowilliams** [comment]
@mamili2 you don't have to share private data, but you do have to share a _sample_ input if you want help.

You should not expect volunteers to setup Kuvernetes just to run `kubectl` or whatever to get a sample in order to help you.  Nor is anyone here going to read the docs for that to make a sample input.

Just anonymize a sample that you have or write a sample from scratch that has the same schema.

**Comment by mook-as** [comment]
In case anybody else lands here due to hitting the same issue:

It appears that the packaging of `jq` in `obs://utilities` isn't quite correct; `jq` did not correctly depend on the same version of `libjq1`. So if you just `zypper install --from=utilities jq`, you end up with `jq 1.6-lp151.25.1` but `libjq1 1.5-lp151.2.3`.  That (probably correctly) triggers an assertion.

The fix was to install from the same repo, `zypper install --from=utilities libjq1`.

In case a test case would be useful, `jq . /dev/null` will trigger the issue.

Apologies for adding issues to your bug tracker that you can't possibly fix.
