### ISSUE TITLE
query doesn't work if json key include "@" on Windows

### ISSUE THREAD

**Issue by watahani** [stedolan/jq#1909]
**Describe the bug**
On Windows environment jq doesn't work for json key include "@".
here is example.

```powershell
> echo '{ "@key": "value" }' | jq '.["@key"]' 
jq: error (at <stdin>:1): watahani is not a valid format
```

**To Reproduce**
Provide a minimal test case to reproduce the behavior.
If the input is large, either attach it as a file, or [create a gist](https://gist.github.com) and link to it here.

![image](https://user-images.githubusercontent.com/28978715/58229850-b4383300-7d6d-11e9-93d1-092b4320ac7e.png)

**Expected behavior**

return value

**Environment (please complete the following information):**
 - OS and Version: [e.g. macOS, Windows, Linux (please specify distro)]
 - jq version [e.g. 1.5]

Windows 10, Powershell

````powershell
> jq --version
jq-1.6
```

**Additional context**
Add any other context about the problem here.

**Comment by pkoppstein** [comment]
Windows consoles have different quoting rules compared to bash-like shells.

You will either have to follow the appropriate rules for the shell you're using, or avoid the problem by putting your data and program into separate files, using the jq invocation pattern: 

    jq -f PROGRAM.jq INPUT.json

## For future reference
I realize that you thought you might have found a bug with jq, but until you're quite sure that you have found a bug, it's usually better to seek assistance at stackoverflow.com using the `jq` tag.  There are many reasons for doing so, not least that if the problem turns out to be slightly different from what you think, chances are that you'll get a more useful answer, or at least a more rapid response.

**Comment by nicowilliams** [comment]
Thanks @pkoppstein.
