### ISSUE TITLE
Question: Using script arguments

### ISSUE THREAD

**Issue by ApertureDevelopment** [stedolan/jq#1910]
I am currently attempting to use a argument with jq, but I always run into errors, here a example:

``./script.sh "{\"json1\": \"Test string with multiline\nand empty spaces\"}"``
```sh
#!/bin/bash
json=$1
variable=$(echo $json | jq -r '.json1')

command.sh "$variable"
```

Responce:
```
fatal: unknown argument 'string'
```

I dont know why it sees string as own argument, I tried putting "", \"\" and no bracets at all

Does anyone know why? ( I am new to bash scripting so sorry if this is a simple problem )

**Comment by pkoppstein** [comment]
> I am new to bash scripting 

Yes, the problems you describe are all related to your misunderstanding of bash.  If you cannot figure our the quoting rules for bash, I'd suggest you post your question at stackoverflow.com, using both the `jq` and `bash` tags to maximize the chance that you'll get at least one answer you'll find useful in a speedy way.

Since this is not a jq question, please also "close" this issue here.  Thanks.

**Comment by ApertureDevelopment** [comment]
@pkoppstein 

Well then, why does this:
```
{"msg":"Problem started at 23:52:03 on 2019.05.23\nProblem name: Docker - TeamCity\nHost: \nSeverity: Average\n\nOriginal problem ID: 885\n","ack":"No","sev":3,"status":"PROBLEM"}
```
cause this:
```
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 6, column 25
```
?

**Comment by pkoppstein** [comment]
It doesn't, at least not using jq 1.3, jq 1.4, jq 1.5 or jq 1.6 on a Mac OS platform.

If you want to file a problem report here, please use the standard template (i.e., what you get when you open a new issue and select "Get started").
