### ISSUE TITLE
Allow assigning invalid JSON values

### ISSUE THREAD

**Issue by shammellee** [stedolan/jq#1911]
I'm importing a JSON file into MongoDB which looks like:
```
{
  ""...",
  "date": "2019-05-25T00:00:00-04:00"
  "..."
}
```

In order for MongoDB to recognize `date` as an actual date, I need to reformat it to look like:
```
{
  ""...",
  "date": {$date: "2019-05-25T00:00:00-04:00"}
  "..."
}
```

As you can see, this requires using invalid JSON. Is this possible with jq? It seems like I can only use valid JSON types.

**Comment by wtlangford** [comment]
In general, no, we're not interested in outputting anything that isn't valid JSON.

That said, I'm not familiar with MongoDB's value syntax. Will it accept this?
```json
{
  "date": {"$date": "2019-05-25T00:00:00-4:00"}
}
```

Otherwise, if you're _absolutely certain_ that the string `"$date":` won't otherwise show up in your JSON, you could always pipe it through sed to remove the quotes around it. (Be careful with this, though, because it can easily break other things, since sed doesn't understand JSON...)

In the future, please ask usage questions like this at stackoverflow.com with the jq tag: https://stackoverflow.com/questions/tagged/jq

We want to keep this issue tracker focused on bugs reports/feature requests.

**Comment by jmatth** [comment]
Just ran a quick test and confirmed the following valid json is imported correctly via `mongoimport` version `4.0.3`:

```
{"_id":{"$oid":"5cea02d164a38c7281c4777c"},"date":{"$date":"2019-05-26T03:06:57.165Z"}}
```

You should be able to add quotes around any unquoted keys and have it work with both `jq` and `mongoimport`. Though if you don't mind me asking, where did you get that input from in the first place? `mongoexport` version `4.0.3` on macOS produced valid json for me to start with. If you're using an old version or something it might be easier to just download the current version of the mongodb tools and redo the export. Even if you're using an old version of the database the new version of the tools should work.

**Comment by shammellee** [comment]
@wtlangford yes it worked as a string. Thanks so much.

@jmatth thanks for the info. The original input date comes from [Calendly](https://calendly.com)
