### ISSUE TITLE
do JQ binaries embed boingboing.html?

### ISSUE THREAD

**Issue by luisapace** [stedolan/jq#1913]
Hi, 
my team would use diego-release 2.1.0 and 2.31.0 and to approve that I've to verify all its licenses and those of its dependencies chain, analyzing their source code.

Both of those diego-release contain JQ blobs, respectively :

- jq/jq-1.5-linux64:
- jq/jq-1.6-linux64.tgz

as indicated in (respectively):

- https://github.com/cloudfoundry/diego-release/blob/v2.1.0/config/blobs.yml
- https://github.com/cloudfoundry/diego-release/blob/v2.31.0/config/blobs.yml

Now, the source code of both levels of JQ contains **_hpricot_** gem (as dependency of **_ronn_** gem): 

- https://github.com/stedolan/jq/blob/jq-1.5/docs/Gemfile.lock
- https://github.com/stedolan/jq/blob/jq-1.6/docs/Gemfile.lock 

The problem is that the gem hpricot (0.8.6 is the last one) downlodable from rubygems.org contains the file https://github.com/hpricot/hpricot/blob/0.8.6/test/files/boingboing.html, that is under CC-NC (Creative Commons Non Commercial) license, that I cannot allow because is a problem for us (and this - give the nature of the license - is for sure also for other companies).

So, my questions are: 

1. is the gem embedded in the two above JQ binary blobs? and if so, has the file boingboing.html been included in it and so in the blobs?
2. if the gems is not contained in those binaries, is there a possibility that will be downloaded from rubygems.org as a runtime dependencies?

Thanks a lot for your help on this.

**Comment by wtlangford** [comment]
Both ruby and the `hpricot` gem are only used as build-time dependencies for generating the documentation (both the manpage and the html site) and are not otherwise used or contained by any releases we manage.

The jq binary itself does not contain any ruby, and is completely isolated from the documentation building process.

I'm not familiar with diego-release, so I don't know what's contained in their blobs, so that question may be best directed to them.

Additionally, after jq 1.6 released, we moved away from the ruby dependency for generating documentation and now use a python script instead (with fewer dependencies).

**Comment by nicowilliams** [comment]
> So, my questions are:
> 
> 1.    is the gem embedded in the two above JQ binary blobs? and if so, has the file boingboing.html been included in it and so in the blobs?

No, absolutely not, they are not included in the jq executables.

> 2.    if the gems is not contained in those binaries, is there a possibility that will be downloaded from rubygems.org as a runtime dependencies?

No, absolutely not, the jq executables will not download anything at runtime, let alone Ruby gems.

**Comment by nicowilliams** [comment]
I'm closing this.  If you have any further questions feel free to ask again, or even reopen.

**Comment by luisapace** [comment]
thanks a lot!
