### ISSUE TITLE
Question: empty in string interpolation

### ISSUE THREAD

**Issue by MondayHopscotch** [stedolan/jq#1927]
I had a quick question regarding string interpolation when an interpolation value results in `empty`. 

Example: the jq 

`. | "hello \(empty)"` 

results in an empty output as opposed to outputting `hello `. Is this intentional? Is there a reason behind it?

Other filters, such as the list filter will still create a list, even if all elements within it result in `empty` (you just get a list of length zero).

**Comment by pkoppstein** [comment]
> Is this intentional? Is there a reason behind it?

Yes on both counts, which is not to say that things won't change.  

Currently, string interpolation is essentially syntactic sugar for string concatenation, so
`"hello \(empty)"` is like `"hello " + (empty|tostring)`, and of course with the main exceptions of  the comma operator and `//`, `empty` is a bit like a black hole, even in object-construction expressions like  '{"a": 1, "b": empty}'.

However, there has been discussion about changing the evaluation of object-construction expressions, so that `'{"a": 1, "b": empty}'` would evaluate to `{"a":1}` instead.

**Comment by MondayHopscotch** [comment]
Interesting. in my head, I had imagined it working more like a list than individual `+` operations. Meaning it would be the equivalent to writing:

`["hello", empty] | add`

But the approach you described makes sense, as well -- just a different take on how to glue it back together.

Thanks!
