### ISSUE TITLE
C API returns empty string for regex groups

### ISSUE THREAD

**Issue by voke** [stedolan/jq#1938]
I try to write a Ruby C Extension for [libjq](https://github.com/stedolan/jq/wiki/C-API:-libjq) but I bumped into an issue that I can't seem to find a solution for.

I will use the following jq filter for my tests:

```shell
jq 'scan("foo(.+)")' <<< '"foobar"'
```
and expect it to return `["bar"]`.

### Part 1

First I wrote a straightforward C program to test the libjq C API:

**hello.c**
```c
#include <string.h>
#include <jq.h>

int main() {

  jv input;
  jv result;
  jv dumped;

  const char *buf = "\"foobar\""; // "foobar"
  const char *prog = "scan(\"foo(.+)\")"; // scan("foo(.+)")
  const char *output;

  jq_state *jq = NULL;
  jq = jq_init();

  input = jv_parse(buf);
  jq_compile(jq, prog);

  jq_start(jq, input, 0);

  result = jq_next(jq);

  dumped = jv_dump_string(result, 0);
  output = jv_string_value(dumped);

  printf("Output: %s\n", output);

  jq_teardown(&jq);

  return 0;

}

```

Compile and run:
```shell
gcc hello.c -o hello -ljq && ./hello
Output: ["bar"]
```

Great! Works as expected!

### Part 2

This is the part where things go wrong. `scan("foo(.+)")` with input `"foobar"` returns an empty string `[""]`.

To reproduce the problem I have hosted a git repo including a Dockerfile and some test code that can be found here: https://github.com/voke/libjq-with-ruby-debug

_(The source code is very simple and it should be easy to follow along)_

#### Quick steps to reproduce the issue (taken from repo above):
```shell
git clone https://github.com/voke/libjq-with-ruby-debug
cd libjq-with-ruby-debug
docker build -t libjq-ruby-ubuntu .
docker run -it libjq-ruby-ubuntu
```

I'm not sure if I miss something obvious but I would be really happy if someone can point me in the right direction.

**Comment by nicowilliams** [comment]
Looking in your repo with the Ruby test code, I see this at the end of your plugin function:

```

  jq_teardown(&jq);

  // To get a new VALUE with your locale’s encoding
  return rb_str_export_locale(rb_str_new_cstr(output));

}
```

I don't know what `rb_str_new_cstr(output)` does, but `output` probably needs to be `strdup()`ed so you can `jv_free(dumped)`.  Also, since the `jv_dump_string()` consumes a reference of its input, you might as well change this:

```
    dumped = jv_dump_string(result, 0);
```

to this:

```
    result = jv_dumpt_string(result, 0);
```

and so on.

Now, I can't tell here why it's not working for you in the context of Ruby.  Maybe there's a different Oniguruma?

It was good that you included a debug trace: we can see that `_match_impl` does the wrong thing early on, though I can't tell why.

**Comment by voke** [comment]
I ended up using a modified version of jq with [onigmo](https://github.com/k-takata/Onigmo) instead of oniguruma.
