### ISSUE TITLE
Error message for incorrect usage of --arg is broken.

### ISSUE THREAD

**Issue by waschmittel** [stedolan/jq#2007]
1. When I do this:
`jq --arg var1`
I get this:
`jq: --arg takes two parameters (e.g. --arg varname value)`

2. However, when I do this:
`jq --arg var1 --arg var2 val`
I get this:
`jq: error: var2/0 is not defined at <top-level>, line 1:`

3. And when I do this:
`jq --arg var1 --arg var2 val -f file`
I get this:
`jq: Could not open var2: No such file or directory`

This is broken and has caused us to look for an error var2 when doing: 
`jq --arg var1 $ENV_VAR --arg var2 val -f file`
when actually ENV_VAR was not set.

All 3 cases (not only the first one) should say:
`jq: --arg takes two parameters (e.g. --arg varname value)`

**Comment by Alanscut** [comment]
hi,@waschmittel 
you can try this example

```
#!/bin/sh
value="hello jq"
echo '{}' |  jq  '{ "value" : $value }'  --arg value "$value" 
echo '[]' | jq  '[$value]'  --arg value "$value"
```
output result
```
{"value" : " hello  jq"}
["hello jq"] 
```

**Comment by nicowilliams** [comment]
Ok, but, how can jq decide that the second `--arg` in `jq --arg var1 --arg var2 val` is not intended to be the value argument for `var1`?  I don't think it can.

> This is broken and has caused us to look for an error var2 when doing:
> `jq --arg var1 $ENV_VAR --arg var2 val -f file`
> when actually ENV_VAR was not set.

Well, yes.  The problem is that the Unix shell is messing with you.  When you write `cmd $var`, you can't predict what `cmd` will see as arguments because Unix shells do crazy things.  You really have to write `cmd "$var"` -- you have to internalize this.  It's very rare that I ever need the shell to do what it does by default, so I almost always write `cmd "$var"` and almost never `cmd $var`.
