### ISSUE TITLE
fix bug json 

### ISSUE THREAD

**Issue by why168** [stedolan/jq#2013]
```shell
-> % echo '{"id":1234567890123456789012,"name":"edwin"}' | jq .
{
  "id": 1234567890123456800000,
  "name": "edwin"
}
```

why?
1234567890123456789012 -> 1234567890123456800000 

version：jq 1.6 already installed

**Comment by wtlangford** [comment]
This is a longstanding issue that has been addressed on master since the release of jq 1.6, where we parse numbers into IEEE754 doubles, which cannot precisely represent _very_ large integers. The master branch now contains a change to use a bigdecimal format for storing numbers, which prevents the precision issue, so long as no math is performed on the number.
