### ISSUE TITLE
evaluating string as RH for assignment?

### ISSUE THREAD

**Issue by pomke** [stedolan/jq#2015]
I'm trying to use JQ as a data source for D&D character sheets (ascii mode!) and I'd like to be able to do some calculations, here is a contrived example:

Say I have some JSON:
{ "str": 10, "dex": 5, "calc": ".str + .dex" }

I'd like to be able to evaluate any string value as a filter, so the above would produce:

{ "str": 10, "dex": 5, "calc": 15 }

Is such a thing possible?

**Comment by pkoppstein** [comment]
> Is such a thing possible?

The answer, alas, is "with great difficulty".

More specifically, it's possible because jq is Turing complete,
but currently jq has neither an "eval" facility or a way to "shell-out".

Writing a sufficiently general "eval" may not be too difficult,
depending on your requirements, but I'd suggest something along the
following lines.

First, instead of writing the expression to be evaluated as a simple
string (`".str + .dex"`), write it as an easily processed bit of JSON, e.g.
`["+", ["str"], ["dex"]]`


Now we can write an 'eval' like so:
```
def eval($expr):
  $expr[0] as $op
  | if $op == "+" then getpath($expr[1]) + getpath($expr[2])
    else .
    end;
```
And use it like so:

```
{ "str": 10, "dex": 5, "calc": ["+", ["str"], ["dex"]]}
| . as $in
| .calc |= (. as $e | $in | eval($e))
```

In future, please consider asking usage questions such as this on stackoverflow.com using the `jq` tag: https://stackoverflow.com/questions/tagged/jq
