### ISSUE TITLE
jq .[0] freeze the computer

### ISSUE THREAD

**Issue by tttp** [stedolan/jq#214]
Hi,

the json I used is the votes in the european parliament. Fairly big file, I wanted to use jq to explore the structure. so 

http://parltrack.euwiki.org/dumps/ep_votes.json.xz

jq .[0] ep_votes.json  does freeze my laptop. Had to reboot (linux 64bit).

is there an option to add to process large files, eg. to avoid reading everything first and do the filter after, or..? 

alternatively, do you know a json parser that does handle large files to extract some items in it I could use as a pre-processor to jq?

**Comment by tttp** [comment]
The man page still references the --online-input (but it's been removed indeed)

**Comment by nicowilliams** [comment]
Not in master.  In master there's a streaming option (`--stream`) that uses a "streaming" parser that parses inputs in an online way.

       ·   --stream:

           Parse  the input in streaming fashion, outputing arrays of path and
           leaf values (scalars and empty arrays or empty objects). For  exam‐
           ple,  "a"  becomes  [[],"a"],  and [[],"a",["b"]] becomes [[0],[]],
           [[1],"a"], and [[1,0],"b"].

           This is useful for processing very large inputs. Use this  in  con‐
           junction with filtering and the reduce and foreach syntax to reduce
           large inputs incrementally.

This means you can parse a single JSON text that's gigabytes and gigabytes long and start producing outputs immediately, but the price you pay is that the input representation is not value that represents the entire JSON text (it can't be, since no parser can be done parsing the whole thing until it's seen the end of it), but a value that represents a path to a node in the structure.

I intend to add utilities to make it easier to deal with this representation, like the ones in the in-tree file `tests/modules/streaming.jq`.  With these it's possible to, for example, that a huge input array of small elements and produce those elements as if they had been top-level values as soon as each of those elements are completely parsed.
