### ISSUE TITLE
jq (version:1.5-1-a5b5cbe) crashes with oomkilled (exit code 137)

### ISSUE THREAD

**Issue by ganga1980** [stedolan/jq#2158]
**Describe the bug**

**To Reproduce**
Provide a minimal test case to reproduce the behavior.
If the input is large, either attach it as a file, or [create a gist](https://gist.github.com) and link to it here.

**Expected behavior**
Jq terminates with exit code :137 (oomkilled) for the following command

curl -LO https://raw.githubusercontent.com/ganga1980/k8s-monitoring-scenarios/master/testdata/xyz.json
podsWithValidContainerId=$(cat xyz.json | jq -r '[.items[] | select( .status.containerStatuses != null and .status.containerStatuses[].containerID != null and  .status.containerStatuses[].containerID != "")]')

**Environment (please complete the following information):**
 - OS and Version: [e.g. macOS, Windows, Linux (please specify distro)]
Ubuntu 18.04
 - jq version [e.g. 1.5]
jq-1.5-1-a5b5cbe

**Additional context**

**Comment by solderjs** [comment]
oomkilled means "Out of Memory".

This is a kernel error.

The source that you gave ( https://raw.githubusercontent.com/ganga1980/k8s-monitoring-scenarios/master/testdata/xyz.json ) is about a megabyte minified.

The query that you gave is incorrect, in that it actually causes the full 4,436 lines of `metadata` to repeat multiple times.

```bash
jq -r '[.items[] | select( .status.containerStatuses != null and .status.containerStatuses[].containerID != null and .status.containerStatuses[].containerID != "")]'
```

```
[
  {
    "metadata": {
      "name": "perf-pod-5847d4f7b7-jnbjs",
      "generateName": "perf-pod-5847d4f7b7-",
      "namespace": "default",
      "selfLink": "/api/v1/namespaces/default/pods/perf-pod-5847d4f7b7-jnbjs",
      "uid": "ce19632a-5f02-497f-b07e-f7226ec432c1",
      "resourceVersion": "1650274",
      "creationTimestamp": "2020-06-24T06:35:06Z",
      "labels": {
        "app": "mylogs",
        "pod-template-hash": "5847d4f7b7"
      },
....
```

Rather than streaming the output to a file (which would result in GIGABYTES of output), you're trying to capture it into a subhell

```bash
$(cat xyz.json | jq ... )
```

Therefore you're running out of RAM from the gigabytes of text that are generated.

I'd suggest that you pull just a few records from `xyz.json` rather than the full 1mb, and that you test your query until you only get the exact results that you want.

If your query is correct, then you need to stream it out to a file rather than putting it in a subshell:

```bash
cat xyz.json | jq ... > big-hass-avocado.json
```

This is most likely not an issue with jq

**Comment by solderjs** [comment]
This seems to work as expected:

```bash
cat xyz.json | jq -r '[.items[] | select( .status.containerStatuses != null )]' > test.json
```

But when selecting on the array, it seems to repeat the full text for each item in the array:

```bash
cat xyz.json | jq -r '[.items[] | select( .status.containerStatuses != null and .status.containerStatuses[].containerID != null)]' > test.json
```

Adding the third selector seems to cause it to do an x^2 operation, doing 19,678,096 iterations on the `metadata` object. I don't understand the `jq` syntax well enough to say whether that's the expected behavior, of if that's truly a bug.

**Comment by wtlangford** [comment]
That's definitely expected behavior and why you're getting the x^2 logic. For posterity, the right way to do this is:
```jq
[.items[] | select(.status.containerStatuses | . != null and (.[] | (.containerID != null and .containerID != "")))]
```
