### ISSUE TITLE
Cannot use the pow() nor pow10() functions

### ISSUE THREAD

**Issue by sebma** [stedolan/jq#2456]
**Describe the bug**
I want to divide an integer representing a throughput in `bits/sec` by `10^9` to get `Gbits/sec` but I get `pow/1 is not defined` errors.

**To Reproduce**
```shell
$ echo 7223210000 | jq -r './pow(10,9) | tostring + " bits/sec"'
jq: error: pow/1 is not defined at <top-level>, line 1:
./pow(10,9) | tostring + " bits/sec"
jq: 1 compile error
$ echo 7223210000 | jq -r './pow10(9) | tostring + " bits/sec"'
jq: error: pow10/1 is not defined at <top-level>, line 1:
./pow10(9) | tostring + " bits/sec"
jq: 1 compile error
```

**Expected behavior**
```shell
$ echo 7223210000 | jq -r './pow(10,9) | tostring + " bits/sec"'
7.22321 bits/sec
$ echo 7223210000 | jq -r './pow10(9) | tostring + " bits/sec"'
7.22321 bits/sec
```

**Environment (please complete the following information):**
 - OS and Version: Linux CentOS 7.9
 - jq version 1.5

**Additional context**
`jq` has been built with maths functions ( `-lm`) : 
```
$ ldd $(which jq) | grep libm
        libm.so.6 => /usr/lib64/libm.so.6 (0x00007fa9155a9000)
$ rpm -qf /usr/lib64/libm.so.6
glibc-2.17-325.el7_9.x86_64
```

**Comment by wader** [comment]
Hey, jq uses ; as argument separator so try pow(10; 9)

**Comment by emanuele6** [comment]
`pow(10,9)` is the same as `pow(10),pow(9)` it calls `pow/1` twice (and `pow/1` doesn't exist).
You want to call `pow/2` with two argument, so you should use `pow(10;9)`.

```
bash-5.1$ jq -n 'pow(10; 9)'
1000000000
```
---

`pow10/1` does not exist. `pow10` exists as `pow10/0`: it takes no arguments and takes a number as input, and outputs the result; you would use it as `9 | pow10`.
But keep in mind that `pow10/0` doesn't work because it is not built correctly:
```
bash-5.1$ jq -n '9 | pow10'
jq: error (at <unknown>): Error: pow10/0 not found at build time
```

**Comment by emanuele6** [comment]
Also i think it would make more sense to just use a number literal.
If you don't want to have to write `1000000000`, you can just use `1e9`.

```bash
jq -r '"\(. / 1e9) bits/sec"'
```

**Comment by sebma** [comment]
Thank you everyone for such fast reaction.

For the `pow()`, my bad I had forgotten that `jq` separated function arguments with `;`

@emanuele6  For pow10, you said : 
> But keep in mind that pow10/0 doesn't work since it is non-standard and it was removed from the GNU C standard library in version 2.27, so it is not available on most systems:
> 
> ```
> bash-5.1$ jq -n '9 | pow10'
> jq: error (at <unknown>): Error: pow10/0 not found at build time
> ```

On my system here, we're still using GNU C v2.17 (<v2.27), therefore `pow10` should be here but it is not : 
```shell
$ rpm -qf /usr/lib64/libm.so.6
glibc-2.17-325.el7_9.x86_64
$ jq -n '9 | pow10'
jq: error: pow10/0 is not defined at <top-level>, line 1:
9 | pow10
jq: 1 compile error
```

**Comment by emanuele6** [comment]
@sebma I just compiled `jq` 1.5 from source, and looked at its source code.
I can confirm that `pow10` was not supported at all in `jq` 1.5 so even if you have a `jq` built on a system that has it, you can't use it from `jq`.
Keep in mind that `jq` 1.5 was released more than 7 years ago.

**Comment by sebma** [comment]
@emanuele6 OK, so in order to be able to use the `pow10` function, one has to use `jq` >= 1.6 and GNU Libc < 2.27, is that correct ?

**Comment by emanuele6** [comment]
@sebma

> @emanuele6 OK, so in order to be able to use the `pow10` function, one has to use `jq` >= 1.6 and GNU Libc < 2.27, is that correct ?

In `jq` 1.6, you can use `pow10/0` and it will exist whether it is supported or not (in `jq` 1.5, it does not exist at all).

If the `jq` binary was built on a system where the presence of `pow10()` was detected at compile time, and is ran on a system that has `pow10()`, it will return the result of calling `pow10()` on the input; otherwise, if it was not detected at build time, `pow10` will always throw an error containing `"Error: pow10/0 not found at build time"` when it is run:

```bash
bash-5.1$ jq -n '9 | try pow10 catch .'
"Error: pow10/0 not found at build time"
```

---

Again, in your case, you don't need to use `pow10/0` or `pow/2` and call a C math function at all; you just want `1000000000` which, in `jq`, like most other programming languages (`perl`, `python`, `java`, `javascript`, `awk`, `fortran`, `go`, `C`, `C++`, `D`, ...) can be written as `1e9`.

**Comment by sebma** [comment]
@emanuele6 Thanks for your explanation.
