### ISSUE TITLE
Numbers longer 17 digits wiped by zeroes in Mac

### ISSUE THREAD

**Issue by SCWR** [stedolan/jq#2460]
in Mac has same error like  https://github.com/stedolan/jq/issues/2396

**Describe the bug**
![image](https://user-images.githubusercontent.com/8925282/182144290-4ab6b75b-a5d6-4691-8e08-4a2539d64d4a.png)

**To Reproduce**
Provide a minimal test case to reproduce the behavior.
If the input is large, either attach it as a file, or [create a gist](https://gist.github.com) and link to it here.

**Expected behavior**
A clear and concise description of what you expected to happen

**Environment (please complete the following information):**
 OS and Version:  macOS
 jq version 1.6 

**Additional context**

**Comment by emanuele6** [comment]
As the comments in the other issue say, this has been fixed by #1752 almost 3 years ago, but only on the master branch of this repository.

But, sadly, there has not been a `jq` release in almost 4 years (1.6).

The issue is not specific to mac: you are just not using a version that contains the fix in #1752. (because it has never been officially released.)

This is an exact duplicate of #2396.

**Comment by wader** [comment]
As a workaround  on macOS for now is to install jq master using `brew install --HEAD jq`

**Comment by SCWR** [comment]
> As a workaround on macOS for now is to install jq master using `brew install --HEAD jq`


Thanks

Can you update the `README.md` ?

Mainly the official website is also old. Many people do not know how to get the latest package

**Comment by wader** [comment]
Had a look and there isn't much installation instructions in README.md atm, maybe there should? but `--HEAD` was already mention in https://github.com/stedolan/jq/wiki/Installation#macos
