### ISSUE TITLE
Doubly-escaped double quotes cause parse error

### ISSUE THREAD

**Issue by hubie** [stedolan/jq#2501]
**Description**
A JSON input file with either a key or value containing a twice-escaped double quote (i.e. `\\\"`) will cause a parse error.  Both of the following examples are valid JSON (at least as far as I and a few other JSON validators are concerned), but `jq` is failing to parse them.

**To Reproduce**

***Absolutely Simplest Example***
Parsing the JSON-escaped string of `\"`:
```
❯ echo '"\\\""' | jq .
parse error: Invalid literal at line 1, column 11
```
Expected: `"\""`

***Slightly More Realistic Example***
`foo` with the JSON-escaped value of `"\"bar\""`:
```
❯ echo '{"foo": "\"\\\"bar\\\"\""}' | jq .
parse error: Invalid numeric literal at line 1, column 20
```
Expected: 
```
{
   "foo":"\"\\\"bar\\\"\""
}
```

**Environment (please complete the following information):**
 - macOS `12.6 (21G115)`
 - jq --version: `jq-1.6`

Thanks!

**Comment by wader** [comment]
Hi, could this be echo unescaping causing confusion?

```sh
$ jq -n '"\\\""'
"\\\""
$ jq . <<< '"\\\""'
"\\\""
$ jq . <<< '{"foo": "\"\\\"bar\\\"\""}'
{
  "foo": "\"\\\"bar\\\"\""
}
```

**Comment by emanuele6** [comment]
I don't think there is any issue with `jq` here.

I think that your problem is probably that you are using `echo`.

The behaviour of `echo` is standardised by POSIX with two possible valid behaviours. The standard behaviour in which echo simply prints its arguments joined by space with a terminating newline \(except if the first argument is `-n`\). And the "extended" (POSIX XSI) behaviour, with which `\n`, `\t`, `\\` and other backslash sequences are expanded. \(See [the POSIX `echo` specification](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html).\)

With Bash, usually, the default behaviour for the `echo` builtin is the standard one in which backslash sequences are not expanded. And, as a non-standard extension, you can use the `-e` option to get the XSI behaviour instead. (and you can use `-E` to enforce the standard behaviour if e.g. the default behaviour is configured to be the XSI behaviour).

The defualt behaviour of the `echo` builtin can be changed with the `xpg_echo` shopt option. (`shopt -s xpg_echo` to make XSI the default, `shopt -u xpg_echo` to not make XSI the default.)

MacOS runs an ancient Bash 3 version (they did not update to Bash 4, and newer versions because they did not want to distribute GPL3 software), but the issue is not that Bash changed the default behaviour of `echo` for Bash 4+ (the default behaviour, in Bash, has always been to not expand backslash sequences by default: `xpg_echo` set to off.); the Bash distributed for MacOS has been purposefully patched by Apple to have the `xpg_echo` shopt option on by default (probably because they wanted full POSIX XSI portability for their `/bin/sh`).

Note that this is not unusual real life behaviour for `echo`. Bash (not the version patched by Apple), and `ksh` don't use the XSI behaviour (at least not by default), but other POSIX shells use it (some even exclusively): e.g. `dash` (debian's `/bin/sh`), and `pdksh`. (public domain ksh, the `/bin/sh` of many BSDs); also non-POSIX shells like `zsh`, use the `XSI` behaviour by default for their `echo`.

If you run `echo '"\\\""'` on its own in your interactive shell in which the `jq` command failed, you will probably see that it doesn't actually print `"\\\""`.

Both of the behaviours are valid standardardised behaviours for the `echo` command, so, techically speaking, the programmer who wrote `echo "$varthatmaycontainbackslashwhichshouldnotbeexpanded" | somecommand` is using `echo` incorrectly and is at fault. 

That is one of the reasons why you should **never** use `echo` in a shell script to print data! (or even messages if they contain slash). Always use `printf` instead; it is the only reliable way to print strings in `sh` (n.b. do not inject strings into the format string of `printf`, use `%s`!).

(if that is not enough of a reason, e.g. `echo "$var"` will print nothing if var is "-n", or even "-neEEeeEEEnEe" in Bash, and there is nothing you can do to make it print that, except use `printf`, as you should be doing anyway.) 

Also note that if you have are using `printf %s\\n "$var" | somecommand`, you could just use a here doc instead.:
```bash
#!/bin/sh --
somecommand <<EOF
$var
EOF
```
In `bash`/`ksh` shells you can use a "here string":
```bash
#!/bin/bash --
somecommand <<< "$var"
```
Creating a process to just run `printf %s\\n`, waiting for it to return, and connecting it with a pipe to `somecommand` is unnecessary work.

---

As another note, if you have JSON in a shell variable and want to pass it to `jq`, you could consider using `--argjson` intead of writing the variable to `jq`'s stdin; this is simpler, and also has the added benefit that `jq` will only accept the variable if the it contains exactly one json values. if `jq` reads from stdin, it will run your `jq` script once for every valid JSON value in the input, so if e.g. the variable is "{} []", it will run your script twice, once for `{}`, and once for `[]`; and, for "{}a" it would run the script once for `{}`, and then fail with a parse error; if you use `--argjson` it would error straight away instead in these cases:
```bash
#!/bin/bash --
var1='["a","b"]' var2='{"x":"ABC"} ["HELLO"]' var3='{"x":123}a'

jq '.[]' <<< "$var1"
# "a"
jq '.[]' <<< "$var2"
# "ABC"
# "HELLO"
jq '.[]' <<< "$var3"
# 123
# parse error: Invalid numeric literal at line 2, column 0

# '$i | .[]' could be '$i[]' in this case, `$i | ...` in general.
jq -n --argjson i "$var1" '$i | .[]'
# "a"
jq -n --argjson i "$var2" '$i | .[]'
# jq: invalid JSON text passed to --argjson
# Use jq --help for help with command-line options,
# or see the jq manpage, or online docs  at https://stedolan.github.io/jq
jq -n --argjson i "$var3" '$i | .[]'
# jq: invalid JSON text passed to --argjson
# Use jq --help for help with command-line options,
# or see the jq manpage, or online docs  at https://stedolan.github.io/jq
```

**Comment by pkoppstein** [comment]
And here is a transcript showing that the problem cannot be reproduced on one particular Mac, running jq 1.6 under either of two very different versions of bash: 
```
$ echo $BASH_VERSION
3.2.57(1)-release
$ echo '"\\\""'  | jq-1.6 .
"\\\""
```
```
$ /usr/local/bin/bash 
$ echo $BASH_VERSION
5.1.16(1)-release
$ echo '"\\\""'  | jq-1.6 .
"\\\""
```
