### ISSUE TITLE
Simplest way to remove elevation from coordinates in json file

### ISSUE THREAD

**Issue by droneeric** [stedolan/jq#2507]
I have coordinates that are presented in a json format (see example below) and occasionally it has the elevation. The system to which I am applying the json will not accept data on the z axis. How can I use jq to cycle through and remove the elevation (z-axis) from the json.

Raw:
`{
    [ 48.2725225,
      12.6538725,
      595.2270812
   ],
   [ 48.2725226,
      12.6654544
   ]
}`

After JQ:
`{
    [ 48.2725225,
      12.6538725
   ],
   [ 48.2725226,
      12.6654544
   ]
}`

**Comment by pkoppstein** [comment]
Unfortunately, neither the "raw" data nor the "after jq" data is JSON, so a trivial solution using jq might not be possible.  But your question indicates you actually are starting with JSON, so please clarify.

Also, since your question is basically a usage question, I would suggest you ask it (suitably revised) on stackoverflow.com using the jq tag and any others that might be appropriate.  See https://stackoverflow.com/questions/tagged/jq

**Comment by droneeric** [comment]
@pkoppstein the samples were the sample of the entire json file showing a single element.  I appreciate the quick response and have taken your advise to write a question in stackoverflow.

https://stackoverflow.com/questions/74657564/how-can-i-take-the-elevation-out-of-a-json-object-so-i-am-left-with-longitude-an

**Comment by pkoppstein** [comment]
Thanks for closing this issue.
