### ISSUE TITLE
Built-in function power10 doesnt seem to exist

### ISSUE THREAD

**Issue by hansonchar** [stedolan/jq#2566]
**Describe the bug**
Under [List-of-Built-in-Functions](https://github.com/stedolan/jq/wiki/jq-Language-Description#List-of-Built-in-Functions):
>pow10/0

But 
```bash
$ jq -nc 'pow10'
jq: error (at <unknown>): Error: pow10/0 not found at build time
```

Furthermore, under [Math](https://stedolan.github.io/jq/manual/#Math), `pow10` is listed as a one-input C-math function, but

```bash
$ jq -nc 'pow10(1)'
jq: error: pow10/1 is not defined at <top-level>, line 1:
pow10(1)
jq: 1 compile error
```

**Environment (please complete the following information):**
```
$ uname -a
Darwin ... 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64 x86_64

$ jq --version
jq-1.6
```

**Comment by emanuele6** [comment]
> Furthermore, under Math, `pow10` is listed as a one-input C-math function, but

Exactly, it only has one input, so you use it as `2|pow10`, not as `pow10(2)` just like the sine function is used as `2|sin`.


Note that a `pow10/0` does in fact exist in your jq, otherwise the script would not compile with a syntax error, and that `jq` only errors when `pow10` is run:
```console
~ $ jq -n '2|try pow10'
~ $ jq -n '2|try pow10a'
jq: error: pow10a/0 is not defined at <top-level>, line 1:
2|try pow10a
jq: 1 compile error
~ $ jq -n '2|select(false)|pow10'
~ $ jq -n '2|select(true)|pow10'
jq: error (at <unknown>): Error: pow10/0 not found at build time
```

Your `jq` does have `pow10/0`, but it is implemented effectively as:
```jq
def pow10:
    error("Error: pow10/0 not found");
```

Support of libc math functions depends on the underlying libc since those `jq` functions are just wrappers around them.
If libc doesn't provide one of those functions, `jq` still provides the `jq` wrapper as a function that error when they are called.

Your system's libc does not support `pow10`, like most other modern systems don't; `pow10` is not defined by the C standard and is an old extension.

This is a duplicate of #2456. You can also read that for more details.

**Comment by hansonchar** [comment]
Interesting!
