### ISSUE TITLE
filter on "string contains"

### ISSUE THREAD

**Issue by billehunt** [stedolan/jq#33]
Perhaps I'm missing it, but I can't see a way to filter based on a value containing a string. Something like

jq 'select(.msg.indexOf('Me") != -1)'

Input
[
{"msg": "Pick Me!", "date": "2012-10-22 04:42:05"},
{"msg": "Not this one","date": "2012-10-22 08:39:53"}
]

Output
{"msg": "Pick Me!", "date": "2012-10-22 04:42:05"},

**Comment by radostyle** [comment]
How do you use this feature?

$ echo '{ "hello":"hi"} ' | jq 'select(.hello contains( "hi"))'
error: syntax error, unexpected IDENT
select(.hello contains( "hi"))              1 compile error

$ echo '{ "hello":"hi"} ' | jq 'select(.hello contains "hi")'
error: syntax error, unexpected IDENT
select(.hello contains "hi")              1 compile error

**Comment by slapresta** [comment]
@radostyle For usage questions, please check out Stack Overflow: http://stackoverflow.com/questions/tagged/jq

Also, remember to read the manual first! It has nice sample programs you can use. http://stedolan.github.io/jq/manual/#containselement

As per your example, a sample working program would be `select(.hello | contains("hi"))`

**Comment by radostyle** [comment]
Thank you Santiago.  I did not realize you had to use the pipe operator '|'
as a test.   I did read the manual but in the manual there is no example
with the pipe operator.  Perhaps I should add one?


On Tue, Jun 23, 2015 at 1:43 PM, Santiago Lapresta <notifications@github.com

**Comment by slapresta** [comment]
@radostyle The manual does have a short section about the pipe operator, although, ironically, I can't link you to it since its name is just the pipe character... still, it should be strongly emphasised in the documentation, given that it is perhaps the most essential part of the language, and it certainly is not right now.

Any documentation changes that make `jq` easier to use are welcome, and heavily encouraged in fact! The documentation is over at [`docs/content/3.manual/manual.yml`](https://github.com/stedolan/jq/blob/master/docs/content/3.manual/manual.yml); some basic and probably outdated information on how to run the documentation server locally can be found [here](https://github.com/stedolan/jq/blob/master/docs/README.md). Serve yourself!

**Comment by nicowilliams** [comment]
> Thank you Santiago.  I did not realize you had to use the pipe operator '|'
> as a test.   I did read the manual but in the manual there is no example
> with the pipe operator.  Perhaps I should add one?

Imagine jq with none of the syntactic short-cuts that it has.  Instead of `.a.b.c` `.["a"]|.["b"]|.["c"]`, and so on.

Now add some syntactic shortcuts back in.  When can we leave out the pipe?  Not that often.  Basically only when the next thing is `.`.  For example, `.a|.b` can be `.a.b`, and `.a|.[]` can be `.a[]` (but not `.a.[]`, oddly enough).  And `select(something)|.a` can be `select(something).a`.  Otherwise the pipe is required.

In particular, `.foo contains "hi"` is just not valid.  jq really wants to know that `"hi"` is an argument expression for the `contains` function, so you need the missing parenthesis (`contains("hi")`), and jq really wants to know that `contains` is what you're sending the output of `.foo` to.  So it has to be `.foo|contains("hi")`.  Because of multiple arities for functions, jq could never evolve to not need those parenthesis.  jq could learn that `EXP<space>EXP` is the same as `EXP|EXP`, but that seems most likely to cause confusion.  The pipe symbol makes things clear: the output(s) of the expression on the left goes to the input of the expression on the right.  (That's probably not so obvious to people whose scripts don't read from left to right, but that's another story.)
