### ISSUE TITLE
Inline strings

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#506]
We could fit strings from zero to 14 bytes long (15, including the C null terminator) in `jv` values.  It's probably worth doing.

**Comment by dtolnay** [comment]
"Failed" attempt can be found at #812. The performance gain turned out not to be so significant. Although inline strings did not seem to hurt in any cases, a speedup existed only for trivial programs and was inconsistent across compilers/hardware. Overall not enough benefit to justify the additional complexity.
