### ISSUE TITLE
if statements require else

### ISSUE THREAD

**Issue by vito-c** [stedolan/jq#608]
```
echo 2 | jq 'if . == 0 then
  "zero"
elif . == 1 then
  "one"
end'
error: syntax error, unexpected end
enderror: Possibly unterminated 'if' statement
if . == 0 then2 compile errors
```

or

```
echo 2 | jq 'if . == 0 then "zero" end'
error: syntax error, unexpected end
if . == 0 then "zero" end                      error: Possibly unterminated 'if' statement
if . == 0 then "zero" end2 compile errors
```

**Comment by eric-brechemier** [comment]
For reference, and to summarize the above discussion,

if you get the error `Possibly unterminated 'if' statement`, your code of the form:

```
if condition then value end
```

must be rewritten as:

```
select( condition ) | value
```

because `if` cannot be used without an `else` clause.

**Comment by pkoppstein** [comment]
@eric-brechemier - Your conclusion is not quite right because "if condition then value end" is not valid jq and therefore inherently ambiguous between the valid jq expressions:

    (1) if condition then value else empty end
    (2) if condition then value else E end

In both cases, the full `if C then V else E end` form is obviously one option; and as you say, (1) is easily dealt with using `select`.  

With respect to (2), if E is `.`, then another option is to define a filter such as `def cond(C;V): if C then V else . end;`

Whereas the case for adding `cond` (as defined above) to builtin.jq is fairly weak, a good case can be made for adding:

    def when(C;V): if C?//null then V else . end;

**Comment by eric-brechemier** [comment]
@pkoppstein I see your point but the invalid `if condition then value end` is what I wrote and the error is what brought me here. I just hope to clarify the solution for the next person who comes here.

**Comment by kaos** [comment]
I see the argument for requiring the else statement, but the error message when it is missing could be improved. It took me a good 15 minutes before I came up with good search terms to find this information, that I was missing the else part.

The fact that the example in the [docs](https://stedolan.github.io/jq/manual/#ConditionalsandComparisons) doesn't compile didn't help matters, btw.
[if-then-else example](https://jqplay.org/jq?q=%27if%20.%20%3D%3D%200%20then%0A%20%20%22zero%22%0Aelif%20.%20%3D%3D%201%20then%0A%20%20%22one%22%0Aelse%0A%20%20%22many%22%0Aend%27&j=2)

**Comment by pkoppstein** [comment]
@kaos - Welcome to jq!  I think you'll find that the problem you ran into when using jqplay is that you didn't adapt the answer for the jqplay environment.  Specifically, the outermost single-quotation
marks that are shown in the command-line invocation must be removed in the jqplay environment. (In a sense, it could be said this is a problem with the documentation for jqplay rather than for jq, the documentation for which does not attempt to cover jqplay.  Hopefully with increased experience, your encounters with this kind of teething issue will greatly diminish in frequency.)
