### ISSUE TITLE
Link with Oniguruma fails on CentOS7(?)

### ISSUE THREAD

**Issue by saifikhan** [stedolan/jq#613]
Hi:
installed oniguruma-devel-5.9.5-3.fc22.x86_64.rpm on my CentOS7 box.
However, on building the source, the following error is seen
$make -j8
make  all-am
make[1]: Entering directory `/home/saifi/workarea/source/jq/jq'
  CCLD     jq
./.libs/libjq.a(builtin.o): In function `f_match':
/home/saifi/workarea/source/jq/jq/builtin.c:613: undefined reference to `OnigSyntaxPerl_NG'
/home/saifi/workarea/source/jq/jq/builtin.c:613: undefined reference to `OnigEncodingUTF8'
/home/saifi/workarea/source/jq/jq/builtin.c:613: undefined reference to `onig_new'
/home/saifi/workarea/source/jq/jq/builtin.c:630: undefined reference to `onig_region_new'
/home/saifi/workarea/source/jq/jq/builtin.c:632: undefined reference to `onig_search'
/home/saifi/workarea/source/jq/jq/builtin.c:707: undefined reference to `onig_foreach_name'
/home/saifi/workarea/source/jq/jq/builtin.c:711: undefined reference to `onig_region_free'
/home/saifi/workarea/source/jq/jq/builtin.c:725: undefined reference to `onig_region_free'
/home/saifi/workarea/source/jq/jq/builtin.c:729: undefined reference to `onig_free'
/home/saifi/workarea/source/jq/jq/builtin.c:618: undefined reference to `onig_error_code_to_str'
/home/saifi/workarea/source/jq/jq/builtin.c:718: undefined reference to `onig_error_code_to_str'
collect2: error: ld returned 1 exit status
make[1]: *** [jq] Error 1
make[1]: Leaving directory `/home/saifi/workarea/source/jq/jq'
make: *** [all] Error 2
$

**Comment by jspc** [comment]
You'll probably need to do two things (I know I did) once installing onigurama.

  * Add the correct path to your libraries path(s)
  * reload this setting

If you run `ldd` against your knackered binary you'll see that libonig.so.2 is not found.

if you create a file at, for example, /etc/ld.so.conf.d/onig.conf with the directory libonig has been installed to:

```bash
$ cat /etc/ld.so.conf.d/onig.conf
/usr/local/lib
```

Then run `ldconfig` and dynamic linking will work.

The output of `make install` more or less tells you this. Otherwise its pretty simple linux,
