### ISSUE TITLE
reduce is a dog (even in jq>1.4)

### ISSUE THREAD

**Issue by pkoppstein** [stedolan/jq#618]
The following function uses "reduce" to emit the "equilibrium indices" of the input array.  An equivalent version written using recurse or foreach runs nicely in jq>1.4 (i.e. those versions that have TCO and foreach), but in both jq 1.4 and jq>1.4, the version using reduce has roughly exponentially worse performance in the length of the input array.  

Here are some gross timings using jq>1.4 (i.e. based simply on "time jq ...") for the following query:  

```
array(N;0) | equilibrium_indices | length
```

```
# N     (u+s in seconds)
#1000  0.19
# 1e4   0.43
# 2e4   1.54
# 3e4   3.43
# 4e4   6.2
# 5e4  10.4
# 6e4  16.5
```

Since the `recurse` and `foreach` versions of this program are fine in jq>1,4, the problem is evidently with the implementation of "reduce".  Hopefully a skilled eye will be able to identify it; if not, then maybe "reduce" should be implemented using "foreach"! 

```
def equilibrium_indices:
  def indices(a):
    reduce range(0;a|length) as $i 
      # state: [ headsum, tailsum, answers]
      ( [ 0, add, [] ];
        .[0] as $h
        | (.[1] - a[$i]) as $t
        | (if $h == $t then .[2] + [$i] else .[2] end) as $ans
        | [ $h + a[$i], $t, $ans ] )
    | .[2];

  . as $in | indices($in);

def array(n;init): reduce range(0;n) as $i ([]; . + [init]);
```

**Comment by nicowilliams** [comment]
OK, so here's the last word on this bug.

The problem was that `FORK` pushes a forkpoint and the `DUP` that follows the `FORK` for the loops in `reduce` and `foreach` wants to pop the value that was on the top of the stack before the `FORK` -- that value is now not on top of the stack, so it can't be popped.

The better fix for this issue is not to add `DUPN` as I did, but to add a variant of `FORK` that pops a value, pushes a forkpoint, then pushes the value popped earlier.  Much simpler and easier to understand.

(A generalization would be to add an operand to `FORK` indicating how many values to pop and re-push after pushing the forkpoint, but since this operand today would only ever be zero or one, it's easier to add a new opcode instead.)

**Comment by leonid-s-usov** [comment]
Hi. 
Came here via commit history, cause I'm sniffing around the place where DUPN is added and this instruction is standing in a way of generalising var destructure.

First of all, kudos for documenting this bug so well cause it was **not** clear at all why one would want to replace a value with null on the stack, and in this way fix performance.

I've considered the possibility of making FORK pop and push, and this won't work, actually. The problem is that fork should provide the same top of the stack for the initial execution and for the backtrack jump. This is achieved by restoring stack pointer to the value at the time of fork point creation.

I believe that a cleaner fix to this issue would be to use a local var for `$dot` and LOADVN it after the fork. WDYT?

**Comment by leonid-s-usov** [comment]
Sorry, on the second thought there is even a simpler fix to this, I guess. 
I've noticed this improvement yesterday but didn't think it could save us much.
The thing is, I don't see why FORK is needed there, at all!

```
  block foreach = BLOCK(gen_op_simple(DUP),
                        init,
                        state_var,
                        gen_op_target(FORK, loop),
                        loop,
                        // At this point `foreach`'s input will be on
                        // top of the stack, and we don't want to output
                        // it, so we backtrack.
                        gen_op_simple(BACKTRACK));
```

You see, the first time FORK is executed it saves fork point and proceeds to `loop`. When loop backtracks, FORK jumps to the next instruction, which is .... a BACKTRACK! So, effectively, FORK is just stopping for a moment to backtrack again! It doesn't look like FORK is needed there.

The backtrack from `loop` would proceed up the stack in the same manner it does today but without stopping at FORK for a moment, and this will solve the issue of a double reference - which is not an issue but rather a _vital property of a FORK instruction_

**Comment by leonid-s-usov** [comment]
For reduce we may benefit from a FORK1 instruction.

What is similar between reduce and foreach - they both don't want the same value after the FORK backtracks (as I showed above, foreach can optimise the fork away completely, but in the current state it just discards the input by backtracking). 
So, the value is only utilised by the first filter of the fork.

What is different between reduce and foreach - reduce _does_ require the FORK because it wants to proceed further with the accumulated value. BUT that instruction is a LOADV, which simply discards the input - it could be a dup, that's it.

```
// reduce
  return BLOCK(gen_op_simple(DUP),
               init,
               res_var,
               gen_op_target(FORK, loop),
               loop,
               gen_op_bound(LOADVN, res_var));
```

Here are the two options I see that avoid the spooky DUPN:
1. FORK1 which pops and pushes one value 
2. STOREV before FORK and LOADVN after fork - which effectively does the same as FORK1 above but in the currently available terms, and wasting a local var frame, and using a semi-magical LOADVN 

P.S. I think that LOADVN should store a jv_invalid() into the frame var, just like the frame initialisation code does. This should mean "the value is consumed" and if one needs to store another value there it must be an explicit action. If one fails, it will assert on stack restore, signifying a programming error.
