### ISSUE TITLE
ER: assertion builtins

### ISSUE THREAD

**Issue by pkoppstein** [stedolan/jq#664]
I would like to propose the addition of `assert` and `asserteq` as builtins, defined along the lines of the appended implementation, which piggy-backs off `debug` and `env`.

The assertion filters defined below are designed so that:

1) if assertion checking is turned off, then the run-time overhead is negligible;
2) the presence of well-formed assertions will not interfere with  normal program flow, even in the case of an assertion violation.

In practice, this means that assertions intended for development or testing can be left in-place in production code.

The key features of the assertion facililty defined here are:
* The input to every assertion filter is always passed through without alteration.
* If assertion checking is turned on, then an assertion violation simply results in an error message being emitted on "standard error".
* Assertions are only checked if the environment variable JQ_ASSERT is set (see below for how to turn assertion checking on or off).

The assertion checking filters are as follows:
```
  asserteq(x; y; msg)     asserteq(x; y)
  assert(x; op; y; msg)   assert(x; op; y)
  assert(x; msg)          assert(x)
  assert
```
where:
-  msg is normally a string to be printed as part of the assertion violation warning;
-  op must be one of the predefined binary operators expressed as a string,
    e.g "==", "!=", "<", "//", "and", etc.

### Examples ###
Example 1:
```$x | asserteq(.; 10)```

The above line always produces the value $x.  The assertion is equivalent to assert($x; "=="; 10).
For example, if assertion checking is on:
```
0 | asserteq(.; 10)
```
produces:
```
["DEBUG:","assertion violation: 0 != 10"]
0
```
The DEBUG line above appears on stderr.

Example 2:
``` null | assert```
produces:
```
["DEBUG:","assertion violation: null"]
null
```
### Rationale for a Builtin Assertion Facility ###
There are several reasons for having a light-weight, unobtrusive assertion facility as a collection of builtins (as opposed, for example, to a library or module), but the main reason is to make it trivially easy to use.  

See for example ```Assertions: A Personal Perspective.``` Tony Hoare, 2002
http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=1203056

Slides: http://extras.springer.com/2002/978-3-642-59413-7/3/rom/pdf/hoare_slides.pdf
 
### JQ_ASSERT ###
Here is a table indicating how the JQ_ASSERT environment variable can be set or unset in various contexts:
```
SHELL          SET                    UNSET
sh bash (etc)  export JQ_ASSERT=1     unset JQ_ASSERT
fish           set -x JQ_ASSERT 1     set -u JQ_ASSERT
csh, tcsh      setenv JQ_ASSERT 1     unsetenv JQ_ASSERT

Windows/DOS    SET JQ_ASSERT=1        set JQ_ASSERT=
Windows:       Start > Control Panel > System > Advanced > Environment Variables
```
### Proposed Implementation ###
```
# Requires a version of jq with debug/0
def assert:
  if env.JQ_ASSERT then (if . then . else . as $in | "assertion violation: \(.)" | debug | $in end)
  else .
  end;
  
def assert(exp; msg):
  if env.JQ_ASSERT then
    (exp as $e | if $e then . else . as $in | "assertion violation: \(msg) => \($e)" | debug | $in end)
  else . end;

def assert(exp):
  if env.JQ_ASSERT then
    (exp as $e | if $e then . else . as $in | "assertion violation: \($e)" | debug | $in end)
   else . end;

def asserteq(x;y;msg):
  def s: (if msg then msg + ": " else "" end) + "\(x) != \(y)";
  if env.JQ_ASSERT then
     if x == y then .
     else . as $in | "assertion violation: \(s)" | debug | $in
     end
   else . end;

def asserteq(x;y): asserteq(x;y;null);

def assert(x;op;y;msg):
  def s: (if msg then msg + ": " else "" end) + "\(x) \(op) \(y)";
  if op == "==" then asserteq(x;y)
  elif op == "!=" then assert(x != y; s)
  elif op == "<" then assert(x < y; s)
  elif op == "<=" then assert(x <= y; s)
  elif op == ">" then assert(x > y; s)
  elif op == ">=" then assert(x >= y; s)
  elif op == "and" then assert(x and y; s)
  elif op == "or" then assert(x or y; s)
  elif op == "//" then assert(x // y; s)
  else ("ignoring invalid assertion: \(x) \(op) \(y)" | debug) as $x | .
  end;

def assert(x;op;y): assert(x;op;y;null);
```

**Comment by joelpurra** [comment]
@pkoppstein: good idea -- but to me, an `assert` *in code* throws an error and stops the execution.

Hoare:

> A collection of aptly placed assertions is what permits a massive suite of test cases to be run overnight, without human intervention. Failure of an assertion triggers a dump of the program state, to be analyzed by the programmer on the following morning.

I also see "code asserts" and "test asserts" as different things, and don't want to treat them the same.

- In code, `assert` throws an error which generates a stack trace/crash report/etcetera. (Call this `Debug::Assert`.)
- In a test harness, `assert` merely indicates that a tested condition was not met by generating an error message. It also marks the current test as unsuccessful. (Call this `Test::Assert`.)

In the quote above Hoare seems to be talking about `Debug::Assert` *in code* throwing errors when executed as part of a test.

---

If you haven't, have a look at code contracts. They would be the next step, after code asserts.

http://research.microsoft.com/en-us/projects/contracts/
http://research.microsoft.com/en-us/projects/contracts/faq.aspx

**Comment by nicowilliams** [comment]
I do want an assert, yes, but I think to get the assertions-off-goes-faster
behavior we'll need the compiler to know about assertion-disabling mode.
Anyways, this will be for after 1.5.

I'm not sure that I want assertions to be catchable (except in a debugger,
which doesn't exist).  Speaking of debuggers, it'd be super nice if tracing
execution (`--debug-trace`) + a `-g` option included file, line, column
info, stack depth, so that an external tool could show a cursor moving
through jq code.

**Comment by nicowilliams** [comment]
@joelpurra  Yes jq test harness that records failures and continues rather
than aborts on first failure would very nice.  This would indeed be
different from an assert intended to be optionally disabled in production
code.  Tripping an assertion should cause a test failure  but not failure
of the harness, so assertion violations do need to be catchable.

I'm thinking we'll need a special file/lineno/column bindings to help with
this, and something of a compile-time conditional (without requiring a
pre-processor nor macros).  All of that is doable.  For debug tracing a new
instruction that does nothing more than emit file/lineno/column would be
very nice.

**Comment by pkoppstein** [comment]
The proposed filters are of course intended to work within the constraints of jq-as-it-exists-today.  Furthermore, they are intended to be compatible with future enhancements to jq.  

Regarding "assertions-off-goes-faster": I think you'll find that if used with reasonable care, the proposed set of assertion filters will be adequate, though of course the more jq knows about assertions, the better.

Regarding assertions triggering *failure*: if the current version of jq had more to offer, then I would have added an option (i.e. an environment ariable, perhaps JQ_ASSERT_FAIL) to cause an assertion violation to fail.  Meanwhile, jq does have `error`, and the proposed filters do have the "msg" argument.

As for a design that *requires* assertion violations to trigger failure, I think that there is ample evidence that such a design in practice usually results in the assertion facility being severely under-utilized or avoided altogether.  

There are thus three possibilities (which can of course be blended):
* a global flag for determining failure mode;
* a per-assertion flag for determining failure mode;
* two sets of assertion filters

Again, nothing in the proposed set of assertion filters precludes future enhancements.

the current version of jq already has "error" LI would have added an option (i.e. an environment variable, e.g. JQ_ASSERT_ERROR) if I thought t (in the existing

**Comment by nicowilliams** [comment]
@pkoppstein  Do you have a reference to any studies to back up that assertion?  (That making assertion violations trigger failure causes programmers to not use assertions.)  Would it matter?  I use assertions and I mean for them to cause failures when tripped; they would be useless otherwise.

A jq assert builtin absolutely should lead to an `error` being thrown.  Perhaps assertion errors should not be possible to catch.

**Comment by nicowilliams** [comment]
An "assertions are ignored so the program goes faster" mode could be provided, either immediately or later, but that's a separable issue from what should happen when an assertion is tripped.

**Comment by nicowilliams** [comment]
Note that yielding an uncatchable error on assertion violation does not mean that a test framework could not be built, just that it would have to be built in C (as `jq --run-tests` is) or using an `eval` (which we would have to build).

**Comment by joelpurra** [comment]
@nicowilliams wrote:
> Note that yielding an uncatchable error on assertion violation does not mean that a test framework could not be built, just that it would have to be built in C (as jq --run-tests is) or using an eval (which we would have to build).

Test frameworks don't actually use `Debug::Assert` -- their `Test::Assert` only does boolean checking: `def Test::Assert($msg; $expected; $actual) if $expected != $actual then appendToTestLog($msg) ...`. 

The test *framework* might collect output from `jq` though, but that would be done by collecting `stdin`/`stderr`. I only mentioned `Test::Assert` because there's a confusion because of the names.

**Comment by nicowilliams** [comment]
@joelpurra  Ah yes, of course, test assertions are a different matter.  Excuse the confusion.

**Comment by pkoppstein** [comment]
@nicowilliams:
> I use assertions and I mean for them to cause failures when tripped ...

Yes, that is a nice option to have.

Although I can't offhand give citations about empirical evidence regarding why some programmers don't use assertions when they could or maybe as much as they should, I would ask you what you think the main reasons are.  In addition, I would ask you to consider these points:

(1) Incorrect assertions

Assertions can be wrong. Having a program stop because of an incorrect assertion is fine for a one-person project or unit-testing, but unacceptable for multi-person projects that have testers who have to spend time setting up the preconditions of most test cases.

(2) Consider these two quotations from Tony Hoare, "Assert Early and Assert Often", 2002
http://www.cs.cornell.edu/courses/CS2110/2014sp/assignments/a0/assertearlyassertoften.pdf)
http://www.cs.ox.ac.uk/files/6184/H2002%20-%20Assertion.pdf

(a) In describing alternative behaviors in response to assertion violations, he wrote: "A common idiom is to give the programmer control over such a range of options by means of different ASSERT
macros." (He mentions ignore/fail/continue.)

That is exactly the case I am making: do not require that assertions always raise an error.

(b) "In all branches of engineering, product test is an essential prerequisite before release to manufacture of a new or improved product. For example, in the development of a new aero jet
engine, an early working model is installed on an engineering test bench for exhaustive trials. This model engine will first be thoroughly instrumented by insertion of test probes at every accessible internal interface. ... The engineer ... never needs to test the assembly as a whole to destruction."

An assertion can thus be viewed as a test probe - something that allows instrumentation, but does not prescribe shutdown.

(3) I don't regard Java's assertion facility as sufficiently modern, but I do agree with this stated goal:

"we want to encourage users to leave asserts in object files so they can be enabled in the field."
(http://docs.oracle.com/javase/7/docs/technotes/guides/language/assert.html)

Users will be more accepting of having assertions turned on in the field if assertion violations do not themselves cause failures (see also the paragraph above about incorrect assertions).

(4) Since Go is a relatively new language, it seems reasonable to suppose that Go libraries reflect some accumulated experience, so consider these two:

a) https://github.com/stretchr/testify#assert-package
"Every assert func returns a bool indicating whether the assertion was successful or not, this is useful for if you want to go on making further assertions under certain conditions."

(Having an assertion failure return false of course violates the orthogonality criterion.  but at least it makes it easy for the programmer to adopt a sound approach.)

b) gocheck provides both "Assert" and "Check". "The only difference between them is that when Assert fails, the test is interrupted immediately, while Check will fail the test, return false, and allow
it to continue for further checks."

**Comment by nicowilliams** [comment]
On Mon, Jan 12, 2015 at 04:15:37PM -0800, pkoppstein wrote:
> (a) In describing alternative behaviors in response to assertion violations, he wrote: "A common idiom is to give the programmer control over such a range of options by means of different ASSERT
> macros." (He mentions ignore/fail/continue.)
>
> That is exactly the case I am making: do not require that assertions always raise an error.

Sure.  I've seen `FOOASSERT()` macros and such.  That's fine, but to me
`assert` means "fail if tripped".  A different builtin (perhaps with the
same name but imported from a different module) could have different
semantics, but `assert` must raise if tripped.  Perhaps I'm just
bringing a lot of C perspective into jq, but anyways, I'm not opposed to
a set of functions with various assert-like semantics.

(E.g., the Illumos kernel has debug assertions that are by default
compiled out and assertions that are by default left in.  One has to
build with different options to either enable the debug assertions or
disable the production assertions.  No one ships kernels with production
assertions turned off, and generally kernels are shipped with debug
assertions disabled.)

> (3) I don't regard Java's assertion facility as sufficiently modern, but I do agree with this stated goal:
> 
> "we want to encourage users to leave asserts in object files so they can be enabled in the field."
> (http://docs.oracle.com/javase/7/docs/technotes/guides/language/assert.html)

jq doesn't have object files (yet; perhaps it never will), so that's
kinda irrelevant, for now anyways :)

> Users will be more accepting of having assertions turned on in the field if assertion violations do not themselves cause failures (see also the paragraph above about incorrect assertions).

Users should mostly not get a choice here.

> b) gocheck provides both "Assert" and "Check". "The only difference between them is that when Assert fails, the test is interrupted immediately, while Check will fail the test, return false, and allow
> it to continue for further checks."

That's good for testing, but surely we want production assertions as well.

**Comment by joelpurra** [comment]
> (1) Incorrect assertions
> 
> Assertions can be wrong. Having a program stop because of an incorrect assertion is fine for a one-person project or unit-testing, but unacceptable for multi-person projects that have testers who have to spend time setting up the preconditions of most test cases.

What? So, if the code is broken, and `assert` is tripped, it should be let go because it's an inconvenience to the QA team that the developers made an error -- or because they made strict `assert`s to ensure a correct program? Assert is not something "extra" for the QA team -- `assert` is code. Code should be correct -- `assert` is used to make sure the code working correctly, protecting other parts of the code from incorrect input and state. It is so very much "fine" for multi-person projects -- that's actually where they shine!

Imagine shipping bad code, because assertions were tripped but it didn't seem it had any effect -- "we in QA assumed it was just a bad assert" -- which then later turns out to be important. It's like writing tests in an external test harness, but ignoring them because they are "probably not correct". If you or your team writes incorrect code, that's a different problem from `assert` failing because pre-/post-/conditions inside the code weren't met *even before* release.


> (2) Consider these two quotations [...]
> (a) In describing alternative behaviors in response to assertion violations, he wrote: "A common idiom is to give the programmer control over such a range of options by means of different ASSERT
> macros." (He mentions ignore/fail/continue.)
> 
> That is exactly the case I am making: do not require that assertions always raise an error.

Then he might be talking about `def debugIfFalse($test): if ($test | not) then debug ...`.


> (b) "In all branches of engineering, product test ... ... The engineer ... never needs to test the assembly as a whole to destruction."
> 
> An assertion can thus be viewed as a test probe - something that allows instrumentation, but does not prescribe shutdown.

You seem to mix `Debug::Assert` (making sure input and state is correct, or fail) with `Test::Assert` (check if test conditions/output is correct, or log) and hardware engineering (it actually *breaks* if you test too much).


> (3) I don't regard Java's assertion facility as sufficiently modern, but I do agree with this stated goal:
> 
> "we want to encourage users to leave asserts in object files so they can be enabled in the field."
> (http://docs.oracle.com/javase/7/docs/technotes/guides/language/assert.html)
> 
> Users will be more accepting of having assertions turned on in the field if assertion violations do not themselves cause failures (see also the paragraph above about incorrect assertions).

This is not what your quote is saying. It says leave `assert`s in place, but have them completely disabled in production code. With a few flags, they can be enabled again, possibly tripping assertions indicating incorrect stat, which would output information valuable to the one debugging.

They also make clear that assert always throws and can't be caught.

From the Programming With Assertions link, with my own highlights.

> #### Why is AssertionError a subclass of Error rather than RuntimeException?
> This issue was controversial. The expert group discussed it at length, and came to the conclusion that **Error was more appropriate to discourage programmers from attempting to recover from assertion failures.** It is, in general, difficult or impossible to localize the source of an assertion failure. **Such a failure indicates that the program is operating "outside of known space," and attempts to continue execution are likely to be harmful.** Further, convention dictates that methods specify most runtime exceptions they may throw (with &at;throws doc comments). It makes little sense to include in a method's specification the circumstances under which it may generate an assertion failure. Such information may be regarded as an implementation detail, which can change from implementation to implementation and release to release.

Random quote 1.

> Programmers of certain critical systems might wish to ensure that assertions are not disabled in the field.

Random quote 2.

> It is a firm requirement that it be possible to enable assertions in the field, for enhanced serviceability.

**Comment by nicowilliams** [comment]
This should be a module.

It could use a `--arg` global to specify whether to ignore assertions, or perhaps an env var.
