### ISSUE TITLE
jq returns 0 if it cannot index object with number

### ISSUE THREAD

**Issue by gdm85** [stedolan/jq#671]
Similar to #667:

```
curl -s https://api.github.com/repos/stedolan/jq/commits/master | jq -r '.[0]'
```

shows:
```
jq: error: Cannot index object with number
```

And an exit code of 0.

**Comment by wtlangford** [comment]
So, that's actually by design.  By default, jq only returns error codes if there's an error in usage, syntax, or compiling.  If you'd also like error codes returned when jq errors, run jq with the `-e` flag. 
```
curl -s https://api.github.com/repos/stedolan/jq/commits/master | jq -e -r '.[0]'
```

**Comment by gdm85** [comment]
Sorry, I only checked the man page that is a placeholder, didn't know about this option!

1) can we add a man page? :)
2) would it be possible to change the default to be with ``-e`` enabled?

I am proposing both (1) and (2) because jq - being a command line interface linux utility - would better service its users by having similar behaviour to other cli tools. Actually one uses jq only to integrate with other shell scripts/utilities.

**Comment by gdm85** [comment]
I see that ``-e`` is not available on 1.3

**Comment by wtlangford** [comment]
If you don't have a manpage with your system package, that's a thing you should take up with the maintainer of it.  The build process definitely builds a manpage, assuming they have the proper environment.  I can say that the website (http://stedolan.github.io/jq/manual/) is built off of the same file as the manpage, so they're identical in that regard. (Though, the website is currently out of sync with some of the features in the 1.4 release, due to some erroneous merges.  Some features on the website haven't made it into a release yet, but that release is very soon!)

As far as changing the default behavior, I might tend to agree with you.  @nicowilliams, is there a reason this is the default behavior?

**Comment by wtlangford** [comment]
Also, that is definitely correct.  Ubuntu 14's package is out-of-date by a fair amount.  If you can build the `jq-1.4` tag from source, that might be your best short-term option.  I'd recommend building master, but it does, occasionally, still break, so just be wary if you choose to.  That being said, master has some significant improvements under the hood.

**Comment by gdm85** [comment]
@wtlangford that's exactly what I am doing now (using jq-1.4 tag), I wanted to leave that comment here for the records (and other users)

Looking forward for ``-e`` being default (can't think of a use-case where you don't want it, but I am biased of course); will follow this discussion.

**Comment by nicowilliams** [comment]
Yes, maybe `-e` should be the default.
