### ISSUE TITLE
`-j` option in manual but throws error

### ISSUE THREAD

**Issue by opennomad** [stedolan/jq#679]
Running version `1.4` and trying to use the `-j` flag I get the following:

jq: Unknown option -j
Use jq --help for help with command-line options,
or see the jq documentation at http://stedolan.github.com/jq

The same happens with `--join-lines`.

The [manual](http://stedolan.github.io/jq/manual/) suggests that the flag exists. The man page does not show it. Seems like the manual is incorrect?

**Comment by wtlangford** [comment]
That's correct. If I remember correctly, -j was introduced after 1.4. We
had some of the features from master leak into the public docs, and that
appears to be one of them.

If you have the ability to build the current master, I'd recommend that.
`brew install jq --HEAD` on a Mac, otherwise you'll have to build it
manually.

**Comment by opennomad** [comment]
Perfect. That helps. I'm ok waiting, but wanted to raise a flag. Thanks for the prompt feedback.
