### ISSUE TITLE
Creating an array from objects?

### ISSUE THREAD

**Issue by dannguyen** [stedolan/jq#684]
First of all, kudos on such an excellent library...I've used jq for basic CLI tasks and have only recently delved into its more advanced functions, and am continually amazed at how things just work with few surprises...rare for a CLI tool that has so many features...

So I think my question is pretty basic, and I'm missing something very obvious that could be clarified in the docs. Given a series of objects, what do I pipe them through to get them into an array? I've found I can do this:

```sh
cat some.json | jq '.[] | { attr1, attr2 }' | jq --slurp '.'
```

...but, that seems like a workaround...is there a more direct function that I'm missing?

**Comment by wtlangford** [comment]
Thanks for the kudos, we're glad to be useful!

There is!  Creating an array from a stream requires knowing when to stop gathering items from the stream, so it isn't done by piping.  To create the array (internally we call this `collect`), just wrap the expression that creates a stream in `[ ... ]`.  So, for your example, `cat some.json | jq '[ .[] | { attr1, attr2 }]'`.  Of course, that's exactly how `map/1` is implemented, so you could (and should!) just as easily do `cat some.json | jq 'map( { attr1, attr2 })'`.   Note, you can also put more complex expressions inside of map too.

**Comment by dannguyen** [comment]
....Ah...I knew it would be something simple...but I gave it up after trying this and getting a list of an arrays:

                  cat some.json | jq '.[] | [{ attr1, attr2 }]

Which makes sense that that *wouldn't* work...but I hadn't thought of wrapping the whole expression in brackets...So yes, again, `jq` was just more sophisticated and natural than I would've expected. Thanks

**Comment by harryjubb** [comment]
@wtlangford Thank you for saving me a huge amount of time!

**Comment by Jolg42** [comment]
@wtlangford Thank you for pointing out the `[ ... ]` solution! 

I was searching for that… It took me a long time to find it…

Maybe this solution can be put in the manual somewhere? For jq's beginners it's not obvious!

**Comment by pkoppstein** [comment]
@jolg42 - The section "Array construction - []" in the manual does cover this topic quite comprehensively, and does emphasize the relevant point several times, for example in the paragraph:

    If you have a filter X that produces four results, 
   then the expression [X] will produce a single result, an array of four elements.

**Comment by thenger** [comment]
`jq-1.5-1-a5b5cbe` here

I'm just adding another example because I struggled with merging multiple maps to one.

Maps where not in a list and contained only one entry.


In my case I add to find stuff in aws so I did this:

```
aws --profile memority --region "eu-west-1" ec2 describe-volumes|jq '.Volumes[]|select(.Encrypted != true)|[{Key: .VolumeId, Value: .Tags?|from_entries|.Name}]|from_entries'
{
  "vol-0e22f37b6b20bdcb7": "active-directory"
}
{
  "vol-032e12cfe27ea6f96": "client1"
}
(...)
```

Basicly:
```
{
  "aaa" : "aval"
}
{
  "bbb" : "bval"
}
```


and the result I wanted was:
```
{
  "aaa" : "aval",
  "bbb" : "bval"
}
```

So I added `'...|reduce . as $m ({}; . + $m)'` which does exactly the same as `'...'|jq -s 'add'` but is longer

I would have loved a `merge` function. 

But maybe my full jq query has no sense 🤔

anyway hth

**Comment by thenger** [comment]
`jq-1.5-1-a5b5cbe` here

I'm just adding another example because I struggled with merging multiple maps to one.

Maps where not in a list and contained only one entry.


In my case I add to find stuff in aws so I did this:

```
aws ec2 describe-volumes|jq '.Volumes[]|select(.Encrypted != true)|[{Key: .VolumeId, Value: .Tags?|from_entries|.Name}]|from_entries'
{
  "vol-0e22f37b6b20bdcb7": "active-directory"
}
{
  "vol-032e12cfe27ea6f96": "client1"
}
(...)
```

Basicly:
```
{
  "aaa" : "aval"
}
{
  "bbb" : "bval"
}
```


and the result I wanted was:
```
{
  "aaa" : "aval",
  "bbb" : "bval"
}
```

So I added `'...|reduce . as $m ({}; . + $m)'` which does exactly the same as `'...'|jq -s 'add'` but is longer

I would have loved a `merge` function. 

But maybe my full jq query has no sense 🤔

anyway hth

**Comment by Braymiler1** [comment]
> ....Ah...I knew it would be something simple...but I gave it up after trying this and getting a list of an arrays:
> 
> ```
>               cat some.json | jq '.[] | [{ attr1, attr2 }]
> ```
> 
> Which makes sense that that _wouldn't_ work...but I hadn't thought of wrapping the whole expression in brackets...So yes, again, `jq` was just more sophisticated and natural than I would've expected. Thanks





https://etl722.github.io/trey82/

**Comment by babhishek21** [comment]
It's a strange feeling to see a supposed "command line" processor be so command line _unfriendly_ for something like this. I understand that wrapping an expression in `[ ]` would wrap results into an array, but most users won't have the foresight to do this while they are building their expression.

I often find myself doing a filter [^1] on an array, and my pipes break because the filter spits out a stream of JSON entities instead of maintaining the original list / array semantic. To fix this, I must now change the entire expression buffer by:
1. figuring out where in the expression I need to put the starting bracket
2. run the cursor back to that starting position
3. figure out where the expression needs to be enclosed in the closing bracket (often end of line)
4. put the cursor back to the ending position

It would be a much simpler and ergonomic experience if we just had an `| toarray` operator instead. 

[^1]: which is confusingly called `select`, but that's a battle for another day
