### ISSUE TITLE
support comments in json

### ISSUE THREAD

**Issue by bhenderson** [stedolan/jq#695]
I'm sorry, I haven't looked at the code yet, but would it be possible to support comments in the json input?

ie.

```
'/*
  * comment
  */
{"foo":"bar"}'
```
is valid json for ruby and perl, but jq complains.

thank you!

**Comment by nicowilliams** [comment]
A parser that permits them would be feasible, but passing them through to the output (and making them accessible to jq programs) is a wholly different story, and not very likely.

**Comment by bhenderson** [comment]
yeah, I don't think they need to be output, just ignored on input. I also don't know what the json spec says. I was surprised that it's valid.

**Comment by slapresta** [comment]
It's not on the spec, and since jq is about JSON, it's probably outside jq's scope.

But, since you know that Ruby and Python support it, you can probably make a nice little program that parses JSON with comments from stdin and outputs JSON without comments to stdout.

**Comment by nicowilliams** [comment]
RFC7159 does not specify comments.  RFC7159 does permit "extensions", but there's not much point to extensions that aren't widely understood (and standardized).

The typical advice given re: comments in JSON, in nearly every case I've seen come up, is this: use an object name (key) to pass comments, something like:

    { "comment": "stuff", ... }

Aesthetically it's ugly, but it works.  You can have many pairs named "comment" in one object, though they may not all get passed along (of course, since many parsers, including jq's, parse objects into a hash table, allowing a single value for any one key).  You can have pairs named "comment<N>" to avoid that problem.  Then your comments will get preserved (though object pair ordering need not be preserved, of course, but jq does try to!).

**Comment by bhenderson** [comment]
just to make sure, I'm not looking to parse the comments, I just was hoping to get jq able to process files that have comments in them. I did end up using ruby to filter them out, but what a bummer that I needed another dependency.

thanks for looking. If I get time I'll work on a PR.

**Comment by nicowilliams** [comment]
Yeah.. If I needed this, I'd probably add a parser option for it :)  If you send a PR... I'll consider it!

**Comment by nicowilliams** [comment]
This is probably not hard to add to the parser, as an option, certainly if you're OK with losing the comments.  If you do that, for the jq executable make it something like `--parse-ignore-comments` or something like that.

**Comment by nicowilliams** [comment]
Also, soon enough I'll have refactored all the input/parser handling in main into utility functions in libjq that could then be used to build a simple builtin for "read a whole file", and then we wouldn't need new command-line options for the jq executable.

**Comment by nicowilliams** [comment]
(Which reminds me to go push that refactoring...)

**Comment by pkoppstein** [comment]
@slapresta wrote:
> ... you can probably make a nice little program that parses JSON with comments from stdin and outputs JSON without comments to stdout.

The ruby script at https://gist.github.com/pkoppstein/f53658395d04ea884e55
evaluates a *single* javascript expression (e.g. with comments) and emits the result as a JSON string. This is useful with `jq fromjson`.

**Comment by nicowilliams** [comment]
This is one of many alternative encoding issues.  Closing.

**Comment by dtolnay** [comment]
See also #402.
