### ISSUE TITLE
"Cannot iterate over null" error not very helpful

### ISSUE THREAD

**Issue by SamHasler** [stedolan/jq#715]
Could it indicate where in the filter it is failing?

**Comment by nicowilliams** [comment]
Yeah, something like a filename, line number, and column number would be nice...  (stack traces too, perhaps).

**Comment by nicowilliams** [comment]
Making run-time errors nicer will be tricky.  The bytecode being interpreted has lost all references to the original code.  Adding those references to the bytecode would not be desirable.  Instead we should have something like what ELF and such do: a "section" with debug symbols.

Stack traces could be useful (because of recursion), but not as useful as a lexical pointer into the jq code where the error occurs.  So we should focus on adding debug symbols to the compiler's output.

**Comment by nicowilliams** [comment]
See #739 and #740.

**Comment by nicowilliams** [comment]
#740 doesn't fix this, FYI.

**Comment by agordon** [comment]
See #752 for a suggested patch to report file/line number on runtime errors.

**Comment by nicowilliams** [comment]
@agordon That's for JSON inputs, not jq code, right?

**Comment by agordon** [comment]
@pkoppstein - yes. the printed file/line refers to the input file, not the JQ code.

**Comment by nicowilliams** [comment]
This is improved now.

**Comment by baxterai** [comment]
Note this feature is still apparently missing as of jq-1.6 - is there a way to print the line number of the "Cannot iterate over null" error?
