### ISSUE TITLE
Help iterating over keys and values in an object

### ISSUE THREAD

**Issue by jkleint** [stedolan/jq#73]
This one's just me abusing the bug tracker as a forum.  :)

I have a single object with lots of keys like this:

```
{
    "k1": {"a": [1]},
    "k2": {"a": [2,3]},
    "k3": {"a": [4,5,6]}
}
```

I'd like to end up with something like:

```
k1 1
k2 2 3
k3 4 5 6
```

(as plain text would be nice, but I suppose I could live with arrays or something).  I can get the keys with `keys` and the values with `.[]`, but I can't figure out how to 'zip' them together.  Help?  Thanks!

**Comment by kenahoo** [comment]
I also came here wondering about this functionality, has anything more straightforward been added to `jq` in the meantime?

**Comment by pkoppstein** [comment]
@kenahoo - This is a very old thread and your question is, given all the changes since 2013, rather vague. 

I would suggest you consult the latest ["Development" version of the manual](https://stedolan.github.io/jq/manual/) and the[ jq FAQ](https://github.com/stedolan/jq/wiki/FAQ).  If you then have a usage question, please ask it at stackoverflow.com with the jq tag.  If you have a specific enhancement request, then you could open a new "ticket" here on github.

**Comment by kenahoo** [comment]
The question is the same as the original question - how to filter over all keys & values in an object.  I did look at the manual & FAQ before I posted.  Sounds like there's no new sugar since this question was originally asked.

Fully agree that Stack Overflow is a superior place to ask the question.

**Comment by pkoppstein** [comment]
@kenahoo - I thought you might be referring to the `zip` functionality, which is now provided by `transpose`.  

Since the release of jq 1.3, `map_values` and `keys_unsorted` have been added; and since the release of 1.5, `walk` was added to master.  Together with all the old grains of sugar (including `with_entries`, which has not been mentioned in this thread), the sugar bowl seems quite full to me!

**Comment by talyian** [comment]
> how to filter over all keys & values in an object

As I read it, the `zip` functionality you wanted is just `to_entries`, which has been around for a while.

```
$ echo '{"a": 1, "b": 2, "c": 3}' | jq -c 'to_entries'
[{"key":"a","value":1},{"key":"b","value":2},{"key":"c","value":3}]
```
Original example:
```
$ echo '{"k1":{"a":[1]}, "k2":{"a":[2,3]}, "k3":{"a":[4,5,6]}}' |\
jq 'to_entries|map([.key] + .value.a|map(tostring)|join(" "))|.[]'
"k1 1"                                                                                                                              
"k2 2 3"                                                                                                                            
"k3 4 5 6"                                                                                                                          
```

**Comment by kenahoo** [comment]
@pkoppstein & @talyian, you're right, `with_entries` and nested filters are exactly what I was looking for, thanks for pointing them out and for your patience!
