### ISSUE TITLE
`$__loc` would be convenient for `error`

### ISSUE THREAD

**Issue by nicowilliams** [stedolan/jq#740]
This:

    ... | if EXP then . else error("error at \($_loc)") end | ...

would be nice.  `$__loc` should be an object with a filename key/value pair and a line number key/value pair.

**Comment by slapresta** [comment]
This would be amazing, although I'm not sure if it makes sense for it to be embedded at the language level. Wouldn't it be better to have the `error()` wrapper be aware of that information and be the one responsible of wrapping it, instead of delegating printing it to the error caller?

That said, I find this problem more often with syntax errors: "shell quoting issues?" makes no sense when I'm running scripts with `-f`!

**Comment by nicowilliams** [comment]
`error` can be used for things other than signalling errors, such as an ad-hoc exception system.  I wouldn't want jq to modify the message being raised.

Adding a `$__loc` that is an object with a filename and line number should suffice.

**Comment by nicowilliams** [comment]
Also, this is common in other programming languages.  E.g., `__FILE__` and `__LINE__` and even `__FUNCTION__`, in C.
