### ISSUE TITLE
output filenames when filtering multiple input files

### ISSUE THREAD

**Issue by sparr** [stedolan/jq#743]
When I do `jq 'whatever' *.json` I can't easily identify which lines of the output were produced by each input file. I'd like to see an option (possibly on by default) to add something like "file1.json:" before each section.

**Comment by nicowilliams** [comment]
Perhaps we could have `$source` variable that names the source of the
current input.

**Comment by pkoppstein** [comment]
The workaround (in bash, for example) is to proceed like so:
```
for f in *.json
do
  jq --arg file "$f" 'whatever' "$f"
done
```
where references to $file in 'whatever' will have the relevant file name.

In fact, I think this workaround is so good that if an "enhancement" is needed, it should wait until after jq 1.5 is released.

**Comment by dtolnay** [comment]
Fixed in #753.

**Comment by vito-c** [comment]
@pkoppstein the problem with the workaround you illustrated is what happens when I am trying to actually run a filter across a group of json files. So for example aggregating objects into an array and I want to know where each object came from.

A way to handle this could be to create an interim json object with the filename added.
```bash
alljson=""
for f in *.json
do
  alljson+=$(jq --arg file "$f" '{"data":.,"file":$file}' "$f")
done
```

**Comment by vito-c** [comment]
I'm really not sure how to use `$__loc__` to get the file and line number.

**Comment by pkoppstein** [comment]
@vito-c - I think `input_filename` is more relevant here.  It's in jq 1.5 and is easy to use.  (See e.g. https://stedolan.github.io/jq/manual).

**Comment by vito-c** [comment]
@pkoppstein I didn't see that one! so good :+1:

**Comment by iamwhil** [comment]
I'm trying to do the same thing ended up with this: 

```
for f in *.json
do
  jq --arg file "$f" '<first bit of query / select statement> | input_filename' "$f"
done
```

**Comment by emanuele6** [comment]
@iamwhil that `--arg file "$f"` seems useless, why do you need to pass it to `jq`?

Also why are you even using a shell loop at all instead of just passing multiple files to `jq`?

```
$ tail -n +1 *.json
==> file1.json <==
{
    "a": "x",
    "b": "d"
}

==> file2.json <==
{
    "b": "d",
    "d": "x"
}

$ jq 'select(has("a"))|input_filename' -- *.json
"file1.json"

$ jq 'select(has("b"))|input_filename' -- *.json
"file1.json"
"file2.json"

$ jq 'select(has("d"))|input_filename' -- *.json
"file1.json"
```

Obviously, if this is used in a shell script, you should be treating filenames more sensibly and output them as NUL delimited raw strings.

Example in `bash`:
```bash
#!/bin/bash -

shopt -s nullglob

mapfile -td '' json_files_that_have_b < <(
    jq -j '
        select(has("b")) | "\(input_filename)\u0000"
    ' -- *.json < /dev/null
)

declare -p json_files_that_have_b

: do stuff with "${json_files_that_have_b[@]}"
```

NB: `< /dev/null` is to make `jq` not wait for input from stdin if no `*.json` files exist in the current directory.

**Comment by sparr** [comment]
@iamwhil @emanuele6 Please stop using this 5-year-old feature request as a discussion thread. The request was closed when the feature was implemented.
