### ISSUE TITLE
Should be able to ignore undefined properties

### ISSUE THREAD

**Issue by mikecarlton** [stedolan/jq#765]
Currently this `echo '{ "a": 1, "b": null }' | jq '{ a, b, c }'` returns
```javascript
{ 
  "a": 1,
  "b": null,
  "c": null
}
````
It would be useful to be able to not include properties that are not defined, e.g.
```javascript
{ 
  "a": 1,
  "b": null
}
````
Is this possible currently?  Cannot find it in the docs (or FAQ even)

**Comment by pkoppstein** [comment]
Here's one approach:
```
def collect(properties):
  . as $in
  | reduce properties[] as $key ({}; if $in|has($key) then . + { ($key): $in[$key] } else . end); 

{ "a": 1, "b": null } | collect( ["a", "b", "c"] )
```
You could also modify the definition of "collect" to accept an object with the "query" keys of interest as its argument.

**Comment by nicowilliams** [comment]
It's interesting, no, that jq has syntax for collecting into arrays but not for collecting into objects, and @pkoppstein's `collect` basically does something like that.  Obviously the problem is that generalizing `{ ident, ident, .., ident }` isn't possible (suppose we allowed `{ .a.b }`, it's clear that the one value should be that of `.a.b`, but what should the key be?  And we can't generalize the `?` operator here either.  Only a utility function like @pkoppstein's `collect/1` can work.

**Comment by pkoppstein** [comment]
By the way, here's a closely-related function for using one object (e.g. {a,b,d}) as a template for extracting information from another:
```
def query(queryobject):
  with_entries( select( .key as $key | queryobject | has( $key ) ));
```
Example:
```
{ "a": 1, "b": null, "c": 3 } | query( {a,b,d} )
#yields:
{ "a": 1, "b": null }
```



```

**Comment by nicowilliams** [comment]
@pkoppstein That's quite clever!

**Comment by nicowilliams** [comment]
This reminds me that a destructuring-bind would be convenient.  Something like:

    ... | dbind [$first, $second, .., $last] | ...

and

    ... | dbind {a: $a, b:[$b_first]} | ...
