### ISSUE TITLE
Having trouble inserting an array into a specific element

### ISSUE THREAD

**Issue by bhourigan** [stedolan/jq#837]
Hi

I'm having some trouble using the slurp function to add the contents of one file into a specific spot into another. 

I've got it working, mostly. However the 'right' array contents is being inserted twice. Once into the spot I'm assigning, and again in the top level json body.

Here's the command I'm using:
```
jq -s '(.[0].provisioners[] | select(.type == "chef-solo") | .json) = .[1].json' left.json right.json
```

The contents of the input files:
Left: https://gist.github.com/d193e2c578fff104538e
Right: https://gist.github.com/e07876d5654c232319d1

The content of the output using the above command:
https://gist.github.com/65a7c8713f69d6502e76

I tried some shortcuts such as del(.json) but that's not the right way to go about it. I must be misunderstanding slurp mode.

**Comment by slapresta** [comment]
Hi!

While we're always glad to answer anyone's questions, the recommended way to ask questions is through [stackoverflow's `jq` tag](http://stackoverflow.com/questions/tagged/jq).

Usually, slurp mode is used in scripts where all elements to be slurped are similar; but I can't think of a reason not to use it in this other way. It seems like the only thing missing from your script is to select the first element of the root array:

`jq -s '(.[0].provisioners[] | select(.type == "chef-solo") | .json) = .[1].json | .[0]' left.json right.json`

Instead of slurping, a very good alternative would be to use the `--argfile` flag, which lifts the contents of a file into a jq variable. This makes for a more readable filter and does lend itself nicely to your purpose (no `.[0]` and `.[1]` nonsense)

`jq --argfile right right.json '(.provisioners[] | select(.type == "chef-solo") | .json) = $right.json' left.json`

Hope this helps!

**Comment by bhourigan** [comment]
Hi!

My apologies. I had submitted an issue previously, and someone was kind enough to help. I'll post to Stackoverflow next time.

It works perfectly. Thanks!
