### ISSUE TITLE
Read a property of JSON file which has '-' in the name

### ISSUE THREAD

**Issue by Sachinmanoj** [stedolan/jq#843]
I am trying to run the below command,
          $  jq .req-number trial.json

but I am getting an error,
          "error: number is not defined
           .req-number     1 compile error"

Below is the screenshot
![3](https://cloud.githubusercontent.com/assets/3833959/8603732/c27c7cc2-2697-11e5-991a-b60f4975ffed.jpg)

Content of trial.json is,
{
	"req-number": 20
}

Note: I cant change the property name

How could I read the value of "req-number"?

**Comment by pkoppstein** [comment]
As the error message indicates, your ".req-number" is being parsed as ".req - number" (subtraction). 

If a key name contains "special characters" (here, "-" is special as it is used for subtraction), the abbreviated form ('.key') cannot be used.  All versions of jq support `.["key"]`; some support `."key"`.

For your future reference, it has been suggested that usage questions such as this be posted at 
http://stackoverflow.com/questions/tagged/jq instead of here, where the focus is on issues related to bugs and enhancements.

**Comment by Sachinmanoj** [comment]
Thank you so much
Below is the command I searched for,
$  jq '.["req-number"]' trial.json (OR)
$  jq '."req-number"' trial.json

And sorry for posting the question here
