### ISSUE TITLE
--in-place should imply -M

### ISSUE THREAD

**Issue by drewrm** [stedolan/jq#850]
With 1.5 RC using the -in-place flag writes ansi escape codes in the file.

    [0m[34;1m"ParameterKey"[0m[1;39m: [0m[0;32m"UpdateTimestamp"[0m[1;39m,

Using --in-place with the -M (monochrome) flag produces plain json as expected.

**Comment by dtolnay** [comment]
The `--in-place` option has been removed since the 1.5 RC because of a sequence of complications, including the one you found. See #704. We are planning to add I/O builtins so that in-place could be implemented as a jq module written in jq itself, instead of built into the program. Until then, the alternative is to use @nicowilliams' adaptor tool https://github.com/nicowilliams/inplace.

**Comment by drewrm** [comment]
Ahh that would explain why I couldn't find the flag on master. Thanks for
the explanation, I can easily work around it for now!

**Comment by svnpenn** [comment]
https://github.com/stedolan/jq/issues/105
