### ISSUE TITLE
Complex assignments bug

### ISSUE THREAD

**Issue by chriskendrick** [stedolan/jq#862]
Looks like a bug to me

This works:
jq '(.posts[] | select(.author == "stedolan") | .comments) |= . + ["terrible."]'<<<'{ "posts": [ { "comments": ["legend"], "author": "Bradman" }, { "comments": ["rad"], "author": "Tesla" }, { "comments": ["okay"], "author": "stedolan" } ] }'

This clearly doesn't work:
jq '(.posts | map(select(.author == "stedolan")) | .[].comments) |= . + ["terrible."]'<<<'{ "posts": [ { "comments": ["legend"], "author": "Bradman" }, { "comments": ["rad"], "author": "Tesla" }, { "comments": ["okay"], "author": "stedolan" } ] }'

Tested on an up to date Amazon Linux distro from a git clone of the master branch of jq jq-1.5rc1-157-gf5a7bba 2015/07/22

**Comment by slapresta** [comment]
I've had the in-place operators do weird things to me as well, although I've never found such an obvious reproduction case. Well done!

Now, I don't really know much about how jq works internally, but I'd say that since `map` is defined as `[.[] | f]`, this is creating a new array with only one element on it, so when you do `.[].comments |= ...`, this gets translated as `.posts[0].comments |= ...`, which is not correct because map "re-sorted" the array. As another example, piping `reverse` through the working example also makes it behave erratically:

`jq '(.posts | reverse[] | select(.author == "stedolan") | .comments) |= . + ["terrible."]'<<<'{ "posts": [ { "comments": ["legend"], "author": "Bradman" }, { "comments": ["rad"], "author": "Tesla" }, { "comments": ["okay"], "author": "stedolan" } ] }'`

Pinging the elders (@pkoppstein, @wtlangford, @nicowilliams) on this.

**Comment by dtolnay** [comment]
The problem is exactly what @slapresta guessed. You can use `path` to see which entries will be set by `|=`:

    jq 'path(.posts | map(select(.author == "stedolan")) | .[].comments)'<<<'{ "posts": [ { "comments": ["legend"], "author": "Bradman" }, { "comments": ["rad"], "author": "Tesla" }, { "comments": ["okay"], "author": "stedolan" } ] }'
    [
      "posts",
      0,
      "comments"
    ]

So it sets `.posts[0].comments]`, as you saw.

I will look into whether we can either

1. make this work as expected, or
2. make this fail loudly when you use `|=` in a way that we know may not work as expected.

**Comment by nicowilliams** [comment]
The LHS of `|=` is supposed to be a path expression.  Not all
jq expressions make good path expressions, but `path` tries to make do.  I
don't see a way to fix this other than raising an error when the LHS is not
a path expression, but it's not clear how to determine that, either at
compile time or at run time...

**Comment by nicowilliams** [comment]
I have't looked in detail, but i suspect making this better isn't feasible,
except in the docs.

**Comment by wtlangford** [comment]
That was my thought as well. Unfortunate, to be sure.

**Comment by slapresta** [comment]
This is definitely a bug. I think it needs to either raise an error when the LHS refers to something that isn't a path expression (preferably at compile time) or actually work correctly. I don't think documenting this would be enough...

**Comment by dtolnay** [comment]
I looked into this a bit. We could make this fail at compile time by modifying the grammar to force LHS of `|=` to be obviously a path expression, like `.a[0]."b"`. I don't think that is reasonable, because there are many perfectly fine uses of `|=` like Chris's first example that this would break.

I think we can make this fail at runtime by modifying the behavior of INDEX inside PATH_BEGIN/PATH_END. It would keep track of the most recent jv produced by INDEX, and enforce that the input of the next INDEX is the same jv. This check would only apply if subexp_nest is 0.

I will work on a PR this weekend.

**Comment by nicowilliams** [comment]
On Wednesday, July 22, 2015, David Tolnay <notifications@github.com> wrote:

> I looked into this a bit. We could make this fail at compile time by
> modifying the grammar to force LHS of |= to be obviously a path
> expression, like .a[0]."b". I don't think that is reasonable, because
> there are many perfectly fine uses of |= like Chris's first example that
> this would break.
>

That was my thought as well.  Calling `select/1` in a path expression is
clearly useful and fine.  We don't to throw the baby out with the bathwater.


> I think we can make this fail at runtime by modifying the behavior of
> INDEX inside PATH_BEGIN/PATH_END. It would keep track of the most recent jv
> produced by INDEX, and enforce that the input of the next INDEX is the same
> jv. This check would only apply if subexp_nest is 0.
>

Yes, that would work, but we might then want a way to run an expression
outside any path building context, something like `unpath(exp)`.  That
would be ugly, but it's probably needed now for other reasons.

So maybe first we need a null path matching enter/leave ops and `unpath`,
then attempt to require that path traversals in path building contexts are
linear.


>

**Comment by nicowilliams** [comment]
The other thing is that no matter what the broken example can't work
because calling `map` is just not useful as it's output is not relevant to
building paths to update in `.`.  At best we can detect that as an error.
But it isn't necessarily the case that operating on a new array or object
in a path expression is wrong, since it might be part of legitimately
computing an index, so raising an error here might be wrong too!. I'd not
want to warn.  We could require that non-linear indexing happen in another
path/non-path sub-context... which would be a non-backward compatible
change, but one which is very unlikely to break anything and which improves
the user experience.

**Comment by dtolnay** [comment]
I think the "legitimately computing an index" part you are worried about will always be at subexp_nest>0 so the check will not apply.

**Comment by nicowilliams** [comment]
> I think the "legitimately computing an index" part you are worried about will always be at subexp_nest>0 so the check will not apply.

Hmm, yeah, I just played with that idea and looked at disassemblies, and indeed, that's the case.

**Comment by nicowilliams** [comment]
Thanks for pointing that out about subexp_nest, and it shows the dangers of
commenting armed with just a smartphone.  Ignore the comments about unpath.

**Comment by dtolnay** [comment]
The fix I proposed is at #864.
