### ISSUE TITLE
partial matches of keys

### ISSUE THREAD

**Issue by afeld** [stedolan/jq#863]
Hi there-
Awesome tool, thanks for it. In trying to come up with a solution for https://github.com/cloudfoundry-community/cf-meteor-buildpack/issues/4, I came across the following challenge (simplified):

Suppose we have JSON that looks like this:

```javascript
{
  "foo": 1,
  "foobar": 2,
  "bar": 3,
  "baz": 4
  // ...
}
```

I want to **grab all the values where the key contains the string "bar"**. The best I could come up with is the following (using `jq` v1.5):

```bash
jq 'to_entries|map(select(.key|test("bar")))|map(.value)'
```

Is there a more concise/clever way of doing this? Thanks in advance!

**Comment by slapresta** [comment]
Hi afeld!

I guess that you could just do this, which roughly reads as «give me an array of the values for the keys that contain the string "bar"»:

`jq '[.[keys[] | select(contains("bar"))]]'`

Of course, you could use `test` instead of `contains`; `contains` has the advantage of working on 1.4. If I were you, I'd go for the option I considered more readable, not the one I considered shorter.

**Comment by slapresta** [comment]
By the way, it is recommended to ask usage questions over at StackOverflow, on the jq tag:

http://stackoverflow.com/questions/tagged/jq

**Comment by afeld** [comment]
Sorry, didn't look hard enough for the instructions about where to ask questions. Thanks for the help!
