### ISSUE TITLE
Put items into object based on array of tags

### ISSUE THREAD

**Issue by borisovg** [stedolan/jq#885]
Sorry for the unhelpful title - not sure how to call this operation.

I would like to transform

````json
{
  "foo": {
    "key1": {
      "attr": "x",
      "tags": [
        "foo"
      ]
    },
    "key2": {
      "attr": "y",
      "tags": [
        "foo",
        "bar"
      ]
    }
  }
}
````

into

````json
{
  "foo": {
    "key1": {
      "attr": "x",
      "tags": [
        "foo"
      ]
    },
    "key2": {
      "attr": "y",
      "tags": [
        "foo",
        "bar"
      ]
    }
  },
  "bar": {
    "key2": {
      "attr": "y",
      "tags": [
        "foo",
        "bar"
      ]
    }
  }
}
````

Basically I want to group my objects by the tag attributes that these objects have (assuming that the object will always have at least one tag).

Is this possible? I can do this quite easily in JavaScript but I'm still having difficulty to adjust my brain to jq way of working with data.

**Comment by dtolnay** [comment]
Try this:

    <input.json jq '.foo | reduce to_entries[] as $item ({}; .[$item.value.tags[]][$item.key] = $item.value)'

This starts with an empty object `{}` and for each entry in the top-level object `foo` it adds that entry into the correct key(s) in the output object based on what tags it contains.

**Comment by borisovg** [comment]
Wow that's amazing - let me chew on this for a bit to try and understand how each bit works...

BTW, I got the example a bit wrong, should be:

````json
{
  "key1": {
    "attr": "x",
    "tags": [
      "foo"
    ]
  },
  "key2": {
    "attr": "y",
    "tags": [
      "foo",
      "bar"
    ]
  }
}
````

So your filter would be adjusted to:

````
<test.json jq 'reduce to_entries[] as $item ({}; .[$item.value.tags[]][$item.key] = $item.value)'
````

**Comment by dtolnay** [comment]
Well let me explain it in a little more detail. It may be useful to someone who finds this issue later.

`to_entries` turns the input object into an array of `{key:..., value:...}` objects. In this case the keys are "key1", "key2", and the values look like `{attr:..., tags:...}`.

`reduce` is a way to go through every item in a stream and use each one to make some change to some shared state. To use it, the array produced by `to_entries` needs to be turned into a stream, which is done by `to_entries[]`. The shared state we start with for `reduce` is `{}`, an empty object. Then for each `{key:..., value:...}` object in `to_entries` we need to add an entry into the right place(s) in the output object.

In the part of `reduce` after the semicolon, `$item` is the `{key:..., value:...}` object coming from `to_entries` and `.` is the state that we have so far, starting with the `{}` empty object and including any changes that have been made by previous entries. The keys in the output object are going to be the tags, so if each item had a single tag instead of an array of tags we could do `.[$item.value.tag]`. Since each item has an array of tags, we can turn the array of tags into a stream so that "the rest of the expression" is done once for each tag. This is `.[$item.value.tags[]]`. So for each tag this gives an object that we need to add the current item into. Adding an item into an object typically looks like `...[$key] = $value` so we do the same thing here. The key is the key of the item in the input object, which is `$item.key`. Similarly the value for that key is `$item.value`. Altogether this gives the update expression `.[$item.value.tags[]][$item.key] = $item.value`, which adds the entry represented by `$item` into all the right tags of the output object `.`.
