### ISSUE TITLE
JSON formatter requires double quoted input

### ISSUE THREAD

**Issue by mfischer-zd** [stedolan/jq#891]
There doesn't seem to be a way to get the `@`-formatters to work without double-quoting their values, which leads to behavior like:

```
$ echo 'hi there' | jq '@json'
parse error: Invalid numeric literal at line 1, column 3

# this works though
$ echo '"hi there"' | jq '@json'
"\"hi there\""
```

Although the latter example does provide the correct output for the input provided, there doesn't seem to be a way to do this:

```
$ echo "hi there" | jq '@json'
"hi there"
$ echo -e "hi\nthere" | jq '@json'
"hi\nthere"
```

**Comment by pkoppstein** [comment]
(1) The "j" in "jq" is for JSON, and so the default assumption, as you found out, is that input is JSON.  Hence the need for double quotation marks in the absence of directives otherwise.
(2) The -R option can be used to "quote" each line of input. Thus:
```
$ echo 'hello there' | jq -R .
"hello there"
```

`@json` by contrast is for stringifying JSON entities.

**Comment by mfischer-zd** [comment]
Ah, thank you.

**Comment by dtolnay** [comment]
Use both -R and -s to deal with your fourth example:

    $ echo -e -n "hi\nthere" | jq -R .
    "hi"
    "there"
    $ echo -e -n "hi\nthere" | jq -R -s .
    "hi\nthere"
