### ISSUE TITLE
Choose line endings

### ISSUE THREAD

**Issue by ghost** [stedolan/jq#92]
On the Windows version at least output lines are ended with carriage return newline `CRLF`, which is of course the Windows default.

However this can cause havoc for Windows users with Cygwin or MinGW, as those systems rely on lines to end with newline `LF` only.

Perhaps a command line switch could be made to enable `LF` line endings. As a workaroud, you can use:

~~~
jq --join-output
~~~

~~~
jq -j
~~~

**Comment by svnpenn** [comment]
@stedolan it took me two years but I finally figured this out. I just need to
add

    set -o igncr

before trying to capture output of any Windows native programs like jq.

[Example][1]
[1]:http://github.com/svnpenn/a/blob/58ab945e48846c6e01602968/misc/reddit.sh#L43

**Comment by svnpenn** [comment]
As a workaroud, you can use

    jq --join-output

Or

    jq | sed :

**Comment by frou** [comment]
Or pipe into `tr` to turn CRLF into just LF:

    jq . x.json | tr -d '\r'

**Comment by hackery** [comment]
http://cygwin.com/cygwin-ug-net/using-textbinary.html says that
> Pipes, sockets and non-file devices are opened in binary mode.

but I'm seeing CRLF in piped output in MinGW64, so there may be something else to consider here.

**Comment by mehrdadn** [comment]
Hi @stedolan, I think this issue is still unresolved. I think there is a confusion between the line endings that are used in raw mode and outside raw mode.

For example, if you type the following into the Command Prompt

    echo "[\n]" | jq -r .

the string between the brackets _must not_ contain a carriage return under **any** platform.  

Now, this command produces an extra _trailing_ newline.  
As far as I can see, this line ending should not exist at all—it is clearly not part of the raw data.  
However, if there is some justification for its existence, _this_ line ending should be platform-specific, i.e. CRLF on Windows. (Or, if in e.g. binary mode, LF.)

This is not an insignificant issue because it is extremely important for the user to be able to perform a perfect decoding of the contents of JSON strings. Any transformations can mess things up. However, the way things are currently, I have to resort to Python for this task, because with `jq` I can't find any way to be sure it's not mutating the string contents.  
It's rather unfortunate as it's possibly one of the most basic tasks one could possibly perform with JSON, so if you might be able to look into fixing it, that'd be awesome. Thank you!

**Comment by mirabilos** [comment]
This is really a problem when using the stand-alone jq-winXX.exe under cmd (batch scripts) where Unix tr(1) is not available. This is almost killing jq for me.

**Comment by mirabilos** [comment]
We cannot use `-j` either. Trying to write `"\u000A"` under jq for Windows produces CRLF, too 😠

**Comment by bukowa** [comment]
If anyone landed here and had the same problem, I solved it by using the `-b` flag.

**Comment by MirKml** [comment]
or use gojq from @itchyny, there is no crlf troubles, same line endings (lf) on linux, windows, mac

**Comment by jaraco** [comment]
> If anyone landed here and had the same problem, I solved it by using the `-b` flag.

With `jq` installed using `winget install jqlang.jq`, the binary flag does not seem to work for me.

```
(jq --binary . src/Test/Deployment/ServiceGroupRoot/Tenants_INT.json) | python -c "import sys; print(sys.stdin.buffer.read(10))"
b'{\r\n  "Conf'
```

Curiously, it does seem to work when the content is piped in (and not read from a file):

```
echo "{}" | jq "." | python -c "import sys; print(sys.stdin.buffer.read(10))"
b'{}\r\n'
echo "{}" | jq --binary "." | python -c "import sys; print(sys.stdin.buffer.read(10))"
b'{}\n'
```

**Comment by jaraco** [comment]
> or use gojq from [@itchyny](https://github.com/itchyny), there is no crlf troubles, same line endings (lf) on linux, windows, mac

I started looking into gojq, but then learned that one of the [key differences](https://github.com/itchyny/gojq?tab=readme-ov-file#difference-to-jq) is that it does not support stable key ordering, so it's not really a good substitute.

**Comment by mirabilos** [comment]
Yeah well, we had to resort to `dos2unix` `:'(`

https://github.com/musescore/MuseScore/pull/6742/commits/5f72d1a980411aecc837c32ca4759803f4b1b5e5#diff-4c012f4b48e4b6cf0f46c98d77cd1e93ddcb45e618733a25ba8af3c077189a91

**Comment by bmaupin** [comment]
> This definitely seems to be Cygwin's problem, not jq's. There's a bunch of ways around this on http://cygwin.com/cygwin-ug-net/using-textbinary.html

Does Bash for Windows use Cygwin under the hood? Because I'm encountering this issue using Bash for Windows.

**Comment by AnrDaemon** [comment]
Let me add to the pile. I've had to use standalone jq with Git-for-windows, because Cygwin's jq failing to correctly parse escapes passed from msys2's bash.
But then to my surprise I discovered that all my filtered JSON files now have CRLF line endings.
That's not what I expected from a tool such as jq.

**Comment by wader** [comment]
@AnrDaemon does add `-b` help? "standalone jq" here is a release from https://github.com/jqlang/jq/releases?

**Comment by AnrDaemon** [comment]
There's no `-b` switch in Cygwin version, nor it is present in Linux version. Such change would be non-portable.
I'm primarily using Cygwin tools on Windows, but native IDE's don't work well with them in certain scenarios.
So I have to resort to native tools on case by case basis.

**Comment by wader** [comment]
I think `-b` is a noop in non-windows builds so should maybe using that and official jq builds is an option that is portable?  sorry i'm not a windows user or developer so can't really help much

**Comment by mirabilos** [comment]
On Tue, 18 Nov 2025, Mattias Wadman wrote:

>I think `-b` is a noop in non-windows builds

It’s not.

$ echo [] | jq -b .
jq: Unknown option -b
Use jq --help for help with command-line options,
or see the jq manpage, or online docs  at https://stedolan.github.io/jq
2|$ _

bye,
//mirabilos
-- 
„Cool, /usr/share/doc/mksh/examples/uhr.gz ist ja ein Grund,
mksh auf jedem System zu installieren.“
	-- XTaran auf der OpenRheinRuhr, ganz begeistert
(EN: “[…]uhr.gz is a reason to install mksh on every system.”)

**Comment by wader** [comment]
@mirabilos strange, what version of jq is this? looking at the history it should be a noop since it was introduced in 1.7 https://github.com/jqlang/jq/commit/0dab2b18d73e561f5118011a65cc9877bf21c110

```sh
$ jq --version
jq-1.8.0
$ jq -b -n null
null
```

**Comment by mirabilos** [comment]
On Tue, 18 Nov 2025, Mattias Wadman wrote:

>@mirabilos strange, what version of jq is this?

1.6, so not even that old. I think people still
use 1.4, too.

**Comment by wader** [comment]
I see, yeap then your out of luck :(
