### ISSUE TITLE
Accept gzip compressed files

### ISSUE THREAD

**Issue by m42e** [stedolan/jq#968]
Hi,

I use a set of files as local storrage for JIRA issues fetched from the rest interface. I only need them from time to time, because the performance and reliability is not as it should be. I'd like to compress them using gzip to save a bit of space.

I'm currently using something like `jq '.fields.reporter.name == "John Doe"' *` to search for issues, and thats really handy but it wont work if the files are compressed.

Do you think it is possible to process gzipped files, or is this something that should be done in another way?

Thanks,
Matthias

**Comment by pkoppstein** [comment]
@m42e - What's wrong with 'gzip -c FILENAME | jq ....' ?

**Comment by m42e** [comment]
Well, it works, But I recognized, that decompressing all the files before running jq on the files is much more time efficient.

Thanks.

**Comment by nicowilliams** [comment]
Some day we may have loadable C-coded modules and I/O modules, and then one could just have this sort of feature.  But we won't make jq itself aware of compression.

**Comment by pkoppstein** [comment]
@m42e - decompression takes a certain amount of time whenever it's done, so I'm wondering if perhaps you aren't relying on some mis-measurements?

Some programs, such as `zgrep`, combine decompression with other functionality, mainly for convenience rather than time-efficiency. `tar` includes an unzipper to provide a kind of guarantee that the contents of an archive can be recovered.  

There are several widely used compressors, some better for some purposes than gzip, so it makes sense to keep jq focused, compact, and interoperable.   Meanwhile, you can create your own `zjq` script :-)

**Comment by thedward** [comment]
The package [moreutils](https://joeyh.name/code/moreutils/) includes a utility called `zrun` which lets you do things like `zrun jq . *`.

For extra cleverness:

> If `zrun` is linked to some name beginning with z, like `zprog`, and the link is executed, this is equivalent to executing `zrun prog`.

For example — assuming you have `~/bin` in your `$PATH` — you can do the following:

    ln -s $(which zrun) ~/bin/zjq

Then you could just execute `zjq . *`

**Comment by nicowilliams** [comment]
Using zrun is tricky because it won't know which arguments are filenames.  E.g., `jq --arg foo bar . baz`, where only `baz` is a filename argument.  This is a better argument for having decompression in jq, but still, the answer to that remains "no".

Use a decent shell so you can say `jq ... "$(gunzip -c ...)"`.

**Comment by kkdd** [comment]
If a jq's ```filter``` doesn't contain ```'|'```, we can make the following shell script:

```console
$ ./jq.sh '.' geojson.json.gz
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Dinagat Islands"
  }
}
$
```

```console
$ cat jq.sh
#!/bin/sh
argarray=()

for ARG in "$@"
do
  case "$ARG" in
    *json.gz)
      if [[ -z "$tempdir" ]]; then
          tempdir=$(mktemp -d "${TMPDIR:-/tmp}"/foo.XXXXXXXXX)
      fi
      tempstr=$(env LC_CTYPE=C tr -dc "a-zA-Z0-9" < /dev/urandom | head -c 9)
      a=$tempdir/$tempstr.json
      gzip -dc "$ARG" > $a 2>/dev/null
      ;;
    * )  a="$ARG" ;;
  esac
  argarray+=( "$a" )  
done

jq $(IFS=' '; echo "${argarray[*]}")

if [[ -n "$tempdir" ]]; then
  rm -rf $tempdir
fi

exit $?
```
