### ISSUE TITLE
bash variable eval and subsitution

### ISSUE THREAD

**Issue by grunhutl** [stedolan/jq#971]
I have a json file in which I have a number of variables that are defined in an external file named variables.sh. How do I use jq to source variables.sh and parse the .json file for evaluation of the variables?

**Comment by pkoppstein** [comment]
@grunhutl - On the one hand you say you have a JSON file but on the other you indicate it contains sh variables, so it's not too clear exactly what that file look like.  I'd suggest you post a clarified version of your question at stackoverflow.com with the "jq" tag, because jq/issues is mainly for bug reports and enhancement requests.  Thank you.

**Comment by nicowilliams** [comment]
@grunhutl You could source it in your shell and export the variables to the environment, then access them via the `env` builtin.
