### ISSUE TITLE
Replacing value in JSON object

### ISSUE THREAD

**Issue by dbclkclk** [stedolan/jq#973]
Hi Folks:

Again this is a fantastic tool that makes JSON troubleshooting much more easier. I have this JSON object:

Ektron:{"ukcategories": {
  "category": {
    "category": {"value": "World Literature"},
    "id": {"value": "3"}
  }
}
}

I wanted a way to change the above format to this:

Ektron:{"ukcategories": {
  "category": {
    "category": "World Literature",
    "id":  "3"
  }
}
}

I have this code but, it doesn't work. Kindly let me know if I'm missing something from my code
     
     cat test.json | jq 'map(if .Ektron.ukcategories.category !=null then   .Ektron.ukcategories.category.category = .Ektron.ukcategories.category.category.value ; .Ektron.ukcategories.category.id = .Ektron.ukcategories.category.id.value else . end) | out.json'

Thanks

**Comment by cfraizer** [comment]
I used this as the input.

{
    "Ektron":
    {
        "ukcategories": {
            "category": {
                "category": {"value": "World Literature"},
                "id": {"value": "3"}
            }
        }
    }
}

And my program is

del(.Ektron.ukcategories.category) + {Ektron: { ukcategories: {
category: (.Ektron.ukcategories.category | [to_entries[] | { key:
(.key), value: (.value | to_entries[].value)}]|from_entries ) } } }

1 Breaking It Down
1.1 Get Rid of Stuff We Don't Want

The first clause is del(.Ektron.ukcategories.category). It takes the input
and returns it with the property "category" removed from "ukcategories":

{
  "Ektron": {
    "ukcategories": {}
  }
}

1.2 Building Up the Replacement

{Ektron: { ukcategories: { category: … } } }

This part just creates an object with a top-level field named "Ektron" with
its value an object with a field named "ukcategories" with its value an
object named "category".

{
  "Ektron": {
    "ukcategories": {
      "category": …
    }
  }
}

1.3 The Magic

The example is a little hard to understand because your fields named
"value" are easy to confuse with the fields named "value" created by
to_entries. To make it easier, in this section, I'm renaming your "value"
field to "ekvalue".

{
    "Ektron":
    {
        "ukcategories": {
            "category": {
                "category": {"ekvalue": "World Literature"},
                "id": {"ekvalue": "3"}
            }
        }
    }
}

1.3.1 Turn an Object into an Array

The clause that gives the value for "category" is the cool part.

(.Ektron.ukcategories.category | [to_entries[] | { key: (.key), value:
(.value | to_entries[].value)}]|from_entries )

It takes the object addressed by .Ektron.ukcategories.category in the input
and transforms it into an array like this:

jq ".Ektron.ukcategories.category | to_entries" <<< '{ "Ektron": {
"ukcategories": { "category": { "category": {"ekvalue": "World
Literature"}, "id": {"ekvalue": "3"} } } } } '

yields

[
  {
    "key": "category",
    "value": {
      "ekvalue": "World Literature"
    }
  },
  {
    "key": "id",
    "value": {
      "ekvalue": "3"
    }
  }
]

1.3.2 Change that Array

jq ".Ektron.ukcategories.category | [to_entries[]| { key: (.key),
value: (.value | to_entries[].value) } ]" <<< '{ "Ektron": {
"ukcategories": { "category": { "category": {"ekvalue": "World
Literature"}, "id": {"ekvalue": "3"} } } } }'

yields

[
  {
    "key": "category",
    "value": "World Literature"
  },
  {
    "key": "id",
    "value": "3"
  }
]

1.3.3 Turn that Array Back into an Object

So, in the previous section we used to_entries twice to turn objects into
arrays objects, each with a property named "key" and a property named
"value". Now we'll use from_entries to turn such an array back into an
object.

jq ".Ektron.ukcategories.category | [to_entries[]| { key: (.key),
value: (.value | to_entries[].value) } ]|from_entries" <<< '{
"Ektron": { "ukcategories": { "category": { "category": {"ekvalue":
"World Literature"}, "id": {"ekvalue": "3"} } } } }'

yields

{
  "category": "World Literature",
  "id": "3"
}

which is what we wanted.
1.4 Put It Back Together

That's the form we wanted the "category" object to have. Let's just plug it
back in to the original structure:

jq "del(.Ektron.ukcategories.category) + {Ektron: { ukcategories: {
category: (.Ektron.ukcategories.category | [to_entries[] | { key:
(.key), value: (.value | to_entries[].value)}]|from_entries ) } } }"
<<< '{ "Ektron": { "ukcategories": { "category": { "category":
{"ekvalue": "World Literature"}, "id": {"ekvalue": "3"} } } } }'

which yields

{
  "Ektron": {
    "ukcategories": {
      "category": {
        "category": "World Literature",
        "id": "3"
      }
    }
  }
}

which is what you wanted.

And you don't really need to rename those "value" fields. The same program
works on your original data:

jq "del(.Ektron.ukcategories.category) + {Ektron: { ukcategories: {
category: (.Ektron.ukcategories.category | [to_entries[] | { key:
(.key), value: (.value | to_entries[].value)}]|from_entries ) } } }"
<<< '{ "Ektron": { "ukcategories": { "category": { "category":
{"value": "World Literature"}, "id": {"value": "3"} } } } }'

yields

{
  "Ektron": {
    "ukcategories": {
      "category": {
        "category": "World Literature",
        "id": "3"
      }
    }
  }
}


Hope this helps.

**Comment by nicowilliams** [comment]
If you want to do this very generically, you can do something like this:

    reduce (paths|select(.[-1]=="value")[0:-1]) as $p (.; setpath($p; getpath($p + ["value"])))

**Comment by pkoppstein** [comment]
Here's a way to perform the substitution wherever it's possible:
```
walk( if type == "object" and .category.category.value and .category.id.value
         then .category |= { "category": .category.value, "id": .id.value }
         else . 
         end)
```
