### ISSUE TITLE
missing JSON object detection

### ISSUE THREAD

**Issue by JanChavel** [stedolan/jq#976]
My JSON data:

    {
      "Tags": [
               {  "Key": "Team",     "Value": "AA" },
               {  "Key": "Division", "Value": "BB" },
               {  "Key": "Name",     "Value": "CC" }
            ]
    }

I'd like to display value of Name ("CC" in example above).
If this value is missing "N/A" should be displayed.
Is there any way how to do that using pure jq ?
What I'm looking for is pure jq replacement for this jq and bash mix:

    a=$( cat json | jq -r '.Tags[] | select( .Key=="Name" ) | .Value' );
    if [ -z $a ]; then a="N/A"; fi
    echo $a

**Comment by dtolnay** [comment]
Try this:

    jq -r '.Tags | from_entries | .Name // "N/A"'

This converts the list of key/value pairs to a map using `from_entries`, then picks out the "Name" in the map. Then it uses the "alternative operator" `//` to produce "N/A" if Name was not in the map.

This requires jq 1.5 in order to understand capitalized "Key" and "Value" in `from_entries`. If you are stuck on jq 1.4 or older, you need to explicitly convert them to lowercase:

    jq -r '.Tags | map({key:.Key, value:.Value}) | from_entries | .Name // "N/A"'

**Comment by JanChavel** [comment]
It works perfectly with my jq 1.4.
After remapping to lowercase even reduce is working, fantastic !

Thank You very much.
