### ISSUE TITLE
Add duplicated key in object

### ISSUE THREAD

**Issue by galindro** [stedolan/jq#979]
How could I add elements to an object with the same key, producing this result?

```json
{
  "IFACE":"eth0",
  "IFACE":"eth1",
  "IFACE":"lo"
}
```

Using + operator, it merges the old key and update its value using the object on the right of the +

```bash
$ a='{"IFACE":"eth0"}'
$ echo $a | jq '.'
{
  "IFACE": "eth0"
}
$ jq '. + {"IFACE":"eth1"}' <<< $a
{
  "IFACE": "eth1"
}
```

**Comment by nicowilliams** [comment]
@galindro Well, you kinda can't.  JSON does allow this, but it doesn't require that applications do what you seem to want.  You can do this with jq by writing your own JSON output function instead of using jq's builtin.  (You can also parse these using the streaming parser, otherwise jq takes only the last value for any key that has multiple values in the same object.)

What application expects this sort of JSON??  It's exceedingly unfriendly to expect multiple values for a key in the same object.

**Comment by galindro** [comment]
My fault @nicowilliams. I need to add objects inside an array, not repeated keys inside the same object.

```json
{
   "ifaces":[
     {"IFACE":"eth0"},
     {"IFACE":"eth1"}
   ]
}
```
Now it is working as expected 
:)

**Comment by nicowilliams** [comment]
Excellent! :)
